INSERT INTO "Shops" ("Name", "Address", "RouteId") VALUES
('co-op city wasana kanda', 'Nawayalathenna Junction , Nawayalathenna ', 17),
('N M Traders', 'No 61 Nuwaraeliya Road, Gampola', 8),
('Nelum Glass House', 'No 27 Kandy Road, Menikhinna', 6),
('3TM Oil Mart', '200/6/A Dodamdeniya, Leemagahakotuwa', 22),
('A K R ZOOM', 'No D 02, Public Marcket , Deltota ', 7),
('A One Traders', 'No 152 colombo Street , Kandy ', 13),
('A S Electronics', 'No 625, Balagolla , Kengalla ', 14),
('A.B Electrical', 'No 14D Medawala Road, Pujapitiya', 5),
('A.C.M COLOUR MART PVT LTD', 'No 234, Gannoruwa Road , Peradeniya ', 23),
('A.C.M Moters', 'No 208/A Handessa , Daulagala', 22),
('A.C.M Moters', '221, Palliyakotuwa, Batugoda, Ambathenna', 5),
('A.C.M.E chef store', 'Barigama Juntion , Barigama', 27),
('A.D Hardwarwe', 'No 2 H Pasgama Raod , Marrasana', 18),
('A.D.A Hardware', 'No 382/1 Kurunegala Road, Wathuwala', 27),
('A.D.A Hardware', 'No 382/1 Kurunegala Road, Wathuwala', 27),
('A.D.A Multy center', 'No 307/ 1 kurunegala Road, Nugewela ', 27),
('A.D.S Moters', 'Pitawalawaththa, Gelioya', 9),
('A.D.S Moters', 'Pilawala Watta, Gelioya ', 9),
('A.G.M Traders', 'Kurunegala Road, werellagama', 27),
('A.G.N sons', 'No 27/A Kalapitya Road, Ukuwela', 10),
('A.H.M Stores', 'no 243 Kandy Road, Kadugannawa', 12),
('A.L.M Stores', 'No 49 Kothamale Road, Nawalapitiya', 19),
('A.L.M. Super', 'No A 57, Dunuwila Road , Akurana ', 4),
('A.M.R Hardware', 'No 62/5  Mathale Road, Akurana, Akurana', 4),
('A.M.S Hardware', 'No-203/1 Ranawana Road, katugasthota, katugasthota', 10),
('A.M.S Hardware', 'No-203/1, Ranawana Road , Katugasthota', 16),
('A.M.S Hradware', '242/A Galpihilla, Gakpilla', 5),
('A.M.S Stores', 'Doragamuwa Road, Doragamuwa ', 20),
('A.M.S Stores', 'Doragamuwa Road, Doragamuwa ', 20),
('A.R Auto center', 'No-28/A matale, katugasthota ', 10),
('A.R.A Moters', 'No 171, Mathale Road , Akurana ', 4),
('A.S.B Hardware', 'Pitawala Watta, Gelioya', 9),
('A.S.M Store', 'No 463 Polgasdeniya, Katugasthota', 27),
('A.S.M Stores', 'Kurunegala Road , Polgasdeniya , Katugasthota ', 27),
('A.S.S Moters', 'No 185/3 Delpitiya , Atabage, Atabage', 24),
('A.V Kirthi Store', 'No 149/6 Parana Nilamba , Galaha ', 7),
('Aathif Traders', 'No.27/ A Soysakalle Road , Nwalapitiya ', 19),
('Aditha Hardware', 'No - 657/ A .Gohagoda Road, Gohagoda, Gohagoda', 10),
('Aditha Hardware', 'No 657/A Gohagoda Road, Gohagoda, Gohagoda', 10),
('Ahas Enterprises', 'No 265/A , Old Gampola Road, Penideniya', 22),
('Aidan Eelecrical', 'No 144 Katugathota Road , Katugasthota', 10),
('Ajith Moters', 'Oruthota , Gagasirigama ', 21),
('Ajith Moters', 'Oruthota , Gagasirigama ', 21),
('Ajith Super', 'No 13 A Madawala Road , Pitiyagedara', 20),
('Ajith Super Stores', 'No 13 A Madawala Road , Pitiyagedara', 17),
('Alawathugoda Hardware', 'No 917 Mathale Road, Alawathugoda', 4),
('Alawathugoda Hardware', 'No 917 Matale Road , Alawathugoda, Alawathugoda', 4),
('Alawathugoda Hardware', 'No 917 Mathale Road, Alawathugoda', 4),
('Alawathugoda Stores', 'No 29, Old Mathale Road , Alawathugoda ', 4),
('Aldeniya Sivilima', 'Kurunegala Road , Aldeniya', 27),
('Aldeniya Sivilima', 'No 07 Aladeniya , Werellagama', 27),
('Ali Auto Parts', 'No 314, Katugathota Road , Kandy ', 10),
('Alokaa Hardware', 'Kandy Road, Kengalla', 14),
('Aluhamba Hardware', 'No 16A Aluamba Hardware, Pilawala', 6),
('Alwathegama Hardware', 'Main street , Medawala, Medawala', 16),
('Ambagasthenna Kade', 'Main Street , Muruthalawa', 23),
('Ambal Stores', 'No 430 Nuwaraeliya Road, Pussellawa', 24),
('Ambigai Store', 'No 60 Gampola Road , Nawalapitiya', 19),
('Ambilmeegama Stores', 'No 88 Colombo Road, Embilmeegama', 15),
('Amila Hardware', 'Daulagala Road, Gadaladeniya ', 15),
('Amila Oil Mart', 'No- 37/3, Medawala, Harispathuwa', 16),
('Amila Store', 'Mathale Road ,, Ambathenna , Katugasthota ', 5),
('Amma Family Super', 'No 70C Hewaheta Road , Galaha ', 7),
('Amunugama Furniture Pvt Ltd', 'No 176/ 6, New Digana Road , Kundasale ', 26),
('Amunugama furniture (pvt) ltd', 'Sirimalwaththa Road, Madawala', 17),
('Amunuthuduwa Moters', 'Hedeniya, Werellagama ', 27),
('Ananda Store', 'No 534 Nuwaraeliya Road , Pussellawa', 24),
('Ananda Stores', 'No 534 Nuwaraeliya Road, Pussellawa', 24),
('Ananda Stores', 'No 531 Piththapitiya , Danthure', 12),
('Ananda Stores', 'No 270 Kandy Road, Wathegama', 17),
('Ananda Stores', 'No 392E Gohagoda Road , Gohagoda ', 10),
('Ananda Stores', 'No 130 /A New Town , Digana ', 14),
('Anantha Steel', 'Main Street , Galaha', 7),
('Anil Stores', 'No 89/1, Dumbara Mawatha , Balagolla , Kengalla ', 26),
('Anura Communication', 'Galaha Road, Hindagala ', 7),
('Anura Hardware', 'Danthure Road , Menikdiwala', 12),
('Anura Hardware', 'govidewanagama junction , kundasale', 26),
('Anura Moters', 'No 9 Gampola Road Gelioya , Gelioya ', 9),
('Anurada Moters', 'No 76/B, Nawalapitiya Road , Ulapane ', 19),
('Appsaras Steel', 'No 73 New Town , Digana ', 14),
('Araliya Fashion', 'Kurunegala Road, werellagama ', 27),
('Araliya Stores', 'Thotadeniya , Marrasaba', 22),
('Ariya Stores', 'Warapitiya, Kundasale ', 26),
('Ariya Stores', 'Warapitiya, Kundasale ', 26),
('Ariya Stores', 'No 480 Owala Junction , Kiribathkubura ', 15),
('Aruna Stores', 'No 38 Gampola Raod , Nawalapitiya', 19),
('Arunalu Stores', 'Digana Road , Pallekele, Kundasale ', 26),
('Arunalu supermart', 'No 442/4 Gohagoda Road, Gohagoda', 10),
('Arunasiri Moters', 'No 1050 A, Kandy Road , Alawathugoda ', 4),
('Asanka Moters', 'Kandy Road , Digana ', 14),
('Asanka Moters', 'Kandy Road , Digana ', 14),
('Ashoka Electrical', 'No 21/20 Yahalathenna kande , Wellegama', 27),
('Ashoka Hardware', 'no 173 Pallemulla Katugasthota, Katugasthota, Katugasthota', 10),
('Asian Moters', 'No 03, Aladeniya Road , Muruthalawa', 23),
('Asiri Hardware', 'No 227/K/1, Daulagala , Handessa ', 22),
('Asiri Hardware and Stores', 'Pichchamalwatha Junction , Gurudeniya ', 18),
('Aslam Stores', 'No 125/1/D, Mariyawatta, Gampola ', 19),
('Asma Mini Mart', 'No 54 Nawalapitiya Road, Gampola', 8),
('Asoka Traders', 'No 102 Main street, Galaga', 7),
('ASSALIHATH JUMMA MOSQUE', 'No 14 , MARIYAWATTA , GAMPOLA ', 8),
('Atels Electrical', 'Yatinuwara Weediya, Kandy', 13),
('Athanayaka Hardware', 'No 324/A/1 Galaha Road , Haloya', 7),
('Aththaragama Stores', 'No 12 Daulagala Road, Elugoda', 22),
('Athula Stores', 'No 13Gurudeniya Road., Ampitiya', 25),
('Audio Solution', 'No 58, Gampola Road , Gelioya ', 9),
('Auto Advance', 'Kahattapitiya, Gampola ', 8),
('Auto Cross', 'No 478, Colombo Road , Pilimathalawa ', 12),
('Auto Lanka Moters', 'No 132/M Gampola Road , Nawalapitiya ', 19),
('Auto Lanka Motors (Pvt) Ltd.', 'No 442/A Matale Road , Alwathugada ', 4),
('Auto Mart Kandy', 'No 241, Yatiwawala, Katugasthota ', 27),
('Auto Parts', 'Hewaheta Road, Delthota ', 7),
('Auto Parts Akurana', 'No 370, Mathale Road , Akurana ', 4),
('Auto Range Moters', 'Yaggahapitiya, Gunnepana ', 6),
('Auto Repair', 'Kandy Road , Gampola', 8),
('Auto Show', 'Matale Road, Akurana ', 4),
('Auto Smart', 'No 33, Mapanawathura Road , Kandy ', 13),
('Auto Spare', 'No 168 Mathale Road, Akurana, Akurana', 4),
('Auto Speed', 'No 143 Mathale Road, Akurana', 4),
('Auto Style (J.R Moters)', 'No 248, Kandy Road , Gampola ', 8),
('Auto Vision', 'No 175, Kandy Road , Madawala ', 17),
('Auto Vision', 'No 390, Kurunegala Road , Aladeniya , Werellagama ', 27),
('Auto Wings', 'No 29/1 Wathegama Road , Wathegama, Wathegama', 17),
('Awaf Electrical', 'Madawala Road, Madawala ', 17),
('Awaf Electrical', 'Madawala Road, Madawala ', 17),
('Ayesha Hardware', 'Medagoda Watakadeniya , Gampola', 8),
('B.M .K Stores', 'No 19 Main Street , Galaha', 7),
('B.M.D Oil Bajaj center', 'Danthure Road , Plimathalawa ', 15),
('B.M.D Oil Mart', 'Centrel Market , Kadugannawa', 12),
('B.M.R Stores', 'Polgolla watha , pollegalla ', 17),
('B.M.R Stores', 'Polgolla watha , pollegalla ', 17),
('Badulu Kumari Grocery', 'Daulagala Road, Pilimathalawa ', 15),
('Bagya Bookshop', 'Sirimalwaththa , Gunnepana', 6),
('Bajaj center', 'No 440 Aladeniya , Werellagama', 27),
('Balagolla Stores', 'No 472 Balagolla , Kengalla', 14),
('Bandara and sons hardware', 'No252 Kurunegala Road, Nugawela ', 27),
('Bandara Moters', 'No 319 , Gampola Road , Peradeniya ', 9),
('Bandara Moters', 'Pussellawa Road , Gampola ', 8),
('Bandara Stores', 'No 485 Senarathgama , Katugasthota ', 27),
('Bandara Stores', 'No 485 Senarathgama , Katugasthota ', 27),
('Bandara Stores', 'Kudugala , Ambathenna ', 4),
('Bandara Super', 'No 88 Main street, Galaha', 7),
('BarakathFarm sahop', 'kandy Road , Pimimathama ', 15),
('Barigama Stores', 'No 487 Aladeniya, Werellagama', 27),
('Basil Stores', 'No 127, Theldeniya Road , Napana, Manikhinna ', 6),
('Basnayaka Store', 'Sirimalwaththa , Ginnepana', 6),
('Bathgala Super', 'Sirimalwaththa , Gunnepana', 6),
('Bike House', 'No 270, Kahattapitiya, Gampola ', 8),
('Bliss Store', 'No 81 Thalathuoya Road, Ampitiya', 25),
('Boralumankada Hardware', 'Nuwaraeliya Road, Gampola ', 8),
('Bosewana Store', 'Main Street , Murithalawa', 12),
('Bosewana Stores', 'Aladeniya Road , Muruthalawa ', 23),
('Boyagoda Stores', 'Main Street , Muruthalawa ', 23),
('Bright Auto Modification', 'No 02, Guhagoda Road , Katugasthota ', 10),
('Bright Electrical', 'No10 Bus stand, Welligalla ', 9),
('Bright Light', 'No 20, New Shopping Complex , Pussellawa ', 24),
('Budara Electrical', 'Digana Road,, Kundasale ', 26),
('Budika Oil Mart', 'NO 19 Hewaheta Road, Rikillagaskada', 11),
('Budika Tire House', 'Padiyapellella Road, Rikillagaskada ', 11),
('Burraq Moters', 'A 9Road 7th mile post , Akurana ', 4),
('C and Y Holdings', 'New Town Gurudeniya, Gurudeniya ', 10),
('C.B.M Moters', 'No 46 Gampola Road, Ulapane ', 19),
('C.C Stores', 'Madanwala , Haguranketha', 11),
('C.C Stores', 'Madanwala , Haguranketha', 11),
('C.K Hardware', 'Buwanekaba Road , Gampola ', 8),
('C.S Book shop and Communication', 'No 04 Bus stand , Gelioya', 9),
('C.S Book shop and Communication', 'No 04 Bus stand , Gelioya', 9),
('Candi Mini Mart', 'Sirimalwaththa , Gunnapana', 6),
('Car News Auto Modification', 'No 482, Colombo Road , Pilimathalawa ', 12),
('Car Plus', 'No 150, Mathale Road , Katugasthota ', 4),
('Car Smart', 'No 171, Mathale Road , Akurana ', 4),
('Car Street', 'No 171/1, Matale Road , Akurana', 4),
('Casamara Hotel', 'Kotugodella weediya , Kandy ', 13),
('Cash / Cheque / Credit', '', 6),
('Central Bajaj', 'No 221/B, Kandy Road , Daulagala', 22),
('Centrel Ceremic', 'No 15 Main Street , Galaha', 7),
('Centrel Hardware', 'No 76/A Nawalapitiya Road, Ulapane ', 19),
('Centrel Stationeries', 'Colombo Street , Kandy ', 13),
('Centrel Stores', 'Mathale Road, Akurana ', 4),
('Ceylon Hardware', 'No-157 Polgolla , Pollgolla , Pollagolla', 17),
('Chamal Hardware', 'no-303/A kuregedara, Haloluwa, Haloluwa', 10),
('Chamila Hardware', 'No 40/A, Kirimatiya Junction , Napana, Gunnepana ', 6),
('Chamila Stores', 'Doranegama Road , Medawala ', 16),
('Chamindu Company(pvt) ltd', 'Nuwaraeliya Road, Pussellawa ', 24),
('Champika Hardware', 'Mawela, Maswela', 24),
('Champion Hardware', 'No 663 Colombo Road, Kadugannawa ', 12),
('Chandana Contruction and Hardware', 'No 220/A Srimath Kudarathwaththa Mawatha, Kandy', 10),
('chandana Moters', 'No 29/1Nawalapiya Road , Gampola', 8),
('Chandana Moters', 'No 29/A Nawalapitiya Road , Gampola', 8),
('Chandana Moters', 'No 19/A Nawalapitiya , Gampola', 8),
('Chandana Supermarket', 'Sri Somananda Mawatha, Gallida , Mailapitita ', 11),
('Chandima Stores', 'No 484/12 Udawela Road, Danthure', 12),
('Chandima Stores', 'No 86 Batugoda , Pujapitiya', 5),
('Chandra Stores', 'Main Street , Bokkawala', 16),
('Chandra Traders (Chandra Tex)', 'No 318, Colombo Road , Pilimathalawa ', 15),
('Chandrasena Storers', 'Pallekubura ', 5),
('Chandrasiri Stores', 'No 154 Colombo Raod, Pilimathalawa', 15),
('Chandrika Stores', 'No 255 Daulagala Road , Handessa', 22),
('Chanuka Farm House', 'Medawala, Harispathuwa', 16),
('Chanuthmini Hardware', 'No 397/1 Doluwa Road, Gampola', 8),
('Charles And Sons', 'No 92 Rajaweediya, Kandy', 13),
('Chathu Motors', 'No - 177/1 Paliyapana , Pujapitiya, Pujapitiya', 5),
('Chathurika Stores', 'No 199/C Main Street , Ulapane ', 19),
('Chinthaka Moters', 'Bus stand ', 11),
('Chinthaka Moters', 'Bus stand ', 11),
('Chinthaka Moters', 'Main Street  Busstand , Haguranketha', 11),
('Chula Hardware', 'Thalabuwenna , Kundasale ', 26),
('Chuti Manike Multy palace', 'Mahiyanganaya Road, Theldeniya ', 21),
('City Ceremic Center', 'No 261/B Polgahamula Juction , Peradeniya', 15),
('City Glass Alluminium', 'No 80 Gampola Road , Nawalapitiya', 19),
('City Glass And Electrical', 'Kandy Road , Nawalapitiya', 19),
('City Glass house', 'No 32 Main Street, Thalathuoya', 25),
('City Hardware', 'no 12 Daulagala Road, Penideniya ', 22),
('City Hardware', 'Uguressapitiya', 27),
('City Hardware', 'No 222/B/2, Daulagala , Handessa ', 22),
('City Light', 'No 265/A Haliiyadda Road, Danthure', 12),
('City Mobile', 'Ragala Road, Haguranketha', 11),
('City Multy Center', 'Main Street , Thalathuoya ', 25),
('City Offset Printers', 'No 63 , Ambagamuwa Road , Nawalapitiya ', 19),
('City Shoe palce', 'No 196/A city shoe Place , Hedeniya , Werellagama', 27),
('City Steel Center', 'No 349 Madawala Road, Katugasthota', 10),
('Cntral Hardware', 'No 20 Kandy Road , Kengalla', 14),
('Co Opperative Heardware', 'No 39 colomb Street , Kandy ', 13),
('Colombo Trade Center', 'No 51, Kotugodalla Street , Kandy ', 13),
('Commercial Hardware', 'No 43 Colombo Street, Kandy', 13),
('Commercial Hardware Stores', 'No 43 Colombo Road, Kandy', 13),
('Conmix Site (Kandy)', 'Seable Place , Kandy ', 13),
('Conmix Site (Kandy)', 'Seable Place , Kandy ', 13),
('Crown glass House', 'No 1 Nawalapitiya Road Gampla', 8),
('Crown Hardware', 'No 17 Dolosbage Road, Nawalapitiya', 19),
('Crown Hardware', 'No 250 Williumgopallawa Mawatha , Kandy ', 13),
('Crown Morters', 'Kandy Road , Gelioya ', 9),
('Crown Moters', 'No 125 /C Kandy Road, Madawala', 17),
('Crown Moters', 'No 125/C Kandy Road MadawalaBazar, Madawala', 20),
('crown moters', 'no 95 gelioya rd , gelioya ', 9),
('Crown Moters', 'Kandy Road, Madawala', 17),
('Crown Moters', 'No 193, Colombo Road , Pilimathalawa ', 15),
('Crown Moters', 'No 409, Wathuwala , Katugasthota ', 27),
('D and K Grocery', 'no 175 Pallemulla, Halokuwa', 10),
('D.C Traders', 'No 398 Kehellawala , Kiribathgoda ', 15),
('D.K. Hardware', 'Kandy Road , Theldeniya ', 21),
('D.K.E TYRE HOUSE HARDWARE', 'No 320, Kandy Road , Yatirawana, Wattegama', 17),
('D.M.S Trade Center', 'No 195, Hedeniya , Werellagama ', 27),
('D.S color Center', 'No 552 Kandy Road, Balagolla', 26),
('D.S Spare parts', 'Mathale Road, Wathegama ', 17),
('D.S.N supermart', 'Gunnepana , Sirimalwaththa', 6),
('Dahana Medicare', 'Nawayalathenna junction , nawayalathenna ', 20),
('Daily Gro Food City', 'No 320/3, Thalawathura, Muruthagahamula', 22),
('Daily Needs', 'No 631/D Balagolla , Balagolla ', 14),
('Daluwaththa Store', 'No 150 Kandy Road , Wathegama, Wathegama', 17),
('Damith Auto Part', 'Gampola Road, Agunawala', 9),
('Damith Store', 'Madanwala , Haguranketha', 11),
('DAMMIKA MODERN HOMES PVT LTD', 'Kandy Road , Teldeniya ', 21),
('Dammika Stores', 'No 26, 05 Kanuwa, Hanthana', 7),
('Dana Trading Company Pvt Ltd', 'No 378/2, Saliyawatta, Gampola ', 8),
('Danajaya Traders', 'No 38/5 Hewaheta Road , Rikillagaskada, Rikillagasakada', 11),
('Danalanka Hardware', 'No 09/01, Uduwawala, Katugathota ', 16),
('Dananjaya Enterprises', ' thispela Road, Haguranketha', 11),
('Dananjaya Spare Parts', 'No 319/C, Henawala, Kadugannawa ', 12),
('Danapala Hardware', 'No 42 Old Mthale Roda, Alawathugoda', 4),
('Danapala Hardware Stores', 'no 47 Old Mathale Road', 4),
('Danthure Hardware', 'No 503  Poththapitiya Road, Danthure', 12),
('Danuka Hardware', 'Colombo Road, Kiribathkubura ', 15),
('Danuka Hardware', 'Colombo Road, Kiribathkubura ', 15),
('Danushka Moters', 'No 61, Nawa Rajawella , Digana', 14),
('Danushka Stores', 'Aruppola Road, Aruppola', 6),
('Danushka Stores', 'Maoya , Haguranketha', 11),
('Dasa Hardware', 'No 32/15, Nidahas Mawatha , Singhapitiya, Gampola ', 8),
('Dasanayaka Super', 'Kandy Road , Gelioya ', 9),
('Data Log', 'Information Systems (Pvt) Ltd, No 2/4/D, Gannoruwa Road , Peradeniya ', 23),
('DATALOG', 'Information Systems Pvt Ltd, No 2 4 D, Gannoruwa Road , Peradeniya ', 23),
('Daulagala Stores', 'Kandy raod , Daulagala ', 22),
('Deeepthi Hardware', 'No 161 Dumbarathenna , Kundasale', 14),
('Deepa Stores', 'Kandy Road, Buwelikada', 14),
('DEEPAL CONSTRUCTIONS', 'D C  WICKRAMANAYAKA, NO 34 MATALE ROAD, AMBATHENNA ', 5),
('Deepamali Hardware', 'Main Street , Thalathuoya', 25),
('Delthota Ceremic', 'No 24 Main street , Delthota', 7),
('Delthota Moters', 'No 58 hewaheta road, Delthota ', 7),
('DENUKA ENGINEERING', 'No 32/4 B, Hedeniya Road, Medawala', 16),
('Deranidhu Super and Pick', 'No- 283 A Yakgahapitiya, Yakgahapitiya', 6),
('Deshan Treders', 'Muruthalawa Road , Aladeniya ', 27),
('Dhahamdi Stores', 'Gallida Raod , Mailapitiya ', 11),
('Dhanya Hardwar', 'No 274 ,A Thalathuoya Road, Ampitiya', 25),
('Dharamarathna Stores', 'Colombo Road, Embilmeegama , Kandy ', 15),
('Dhoni Bajaj', 'Panvila Road, Wathegama ', 17),
('Dhoni Bajaj', 'Panvila Road, Wathegama ', 17),
('Diamand Hardware', 'No 107A Batagalla Road, Pujapitiya', 5),
('Didula Hardware', 'Kurunegala Road, Yatiwawala', 10),
('Didula Hardware', 'No 280, Yatiwawala , Katugasthota ', 27),
('Dilshan Audio', 'No 24 Bolepa, Maraasana', 18),
('Dilshani Food center', 'No 79 Ampitiiya Road, Ampitiya', 25),
('Dinesh Hardware', 'No 70/1 A Pilawala , pilawala', 6),
('DINETH MOTORS', 'No 79, Main Street , Pujapitiya ', 5),
('Dinmas Book Shop', 'Kerapane Road , Gampola ', 8),
('Dissanayaka Hardware', 'Bokkawala , Kuburegama', 27),
('Dissanayaka Hardware', 'No 105 Gonapola , Batugoda, Batugoda', 5),
('Dissanayaka hw', 'no -85/3, Atharagama, Mewada', 16),
('Dissanayaka Moters', 'No -67 kandy Road Rikillagaskada, Rikillagaskada', 11),
('Dissanayaka stores', 'Krunegala Road, Nugawela', 27),
('DIVYA SUPER', 'No 67, Thalathuoya Road , Ampitiya ', 25),
('Diwya Enterprise', 'Hewaheta Road, Rikillagaskada', 11),
('DMK HARDWARE', 'No 65 /3/1, Ruwangalawatta, Palliwela, Polgolla', 17),
('Doragamuwa Hardware', 'No 21/A Doragamuwa Road, Pollgalla', 20),
('Doragamuwa Stores', 'No 15 Thalawinna Bazar , Udathalawinna ', 20),
('DS MARKETING AND HARDWARE', 'DEHIPE, PADIYAPELELLA ', 11),
('Dubai Center', 'No 23 Kothamale Road, Nawalapitiya', 19),
('Dulancha Moters', 'No 48/c Thennakubura', 26),
('Dulanjaya Hardware', 'No 134 Kandy Road, Kadugannawa', 12),
('Dumbara Lucky Treders', 'No 10 Muruthalawa Road , Aladeniya , Werellagama', 27),
('Dumbara Stores', 'No 08 main Street Gelioya, Gelioya', 9),
('Dumbara Traders', 'No17/03, Madawala rd, Polgolla, Madawala', 17),
('Duminda Auto Electronics', 'No 05 D, New Town , Kundasale ', 26),
('Duminda Moters', 'No 51, Embllmeegama, Pilimathalawa ', 15),
('Durga Store', 'No 134 Wahugahaputiya , Pussellwa, Pusselawa', 24),
('DYCAR (PVT) LIMITERD', 'No 145, Matale Road , Akurana ', 4),
('E-Max Electrical', 'No 215 ,Pallemulla, Haloluwa', 10),
('E.A.J Hardware', 'No 20/10 Hindagala , Mahakanda', 7),
('E.C.H Globle', 'No 217 Elugoda , Peradeniya ', 22),
('Earth Star Trading', '213/1 Colombo Street , Kandy', 13),
('Ebilmeegama Stores', 'no 88,90 colombo Road , Pilimathalawa ', 15),
('Ekanayaka Grocery', 'No 198 7 kanuwa , Gelioya ', 9),
('Ekanayaka Store', 'No-12 Pujapitiya Road ,, Ambathenna, Ambathenna', 5),
('Ekanayaka Stores', 'No 211 Sirimalwaththa Road, Menikhinna', 6),
('Ekanayaka Stores', 'Mahiyanganaya Road, Theldeniya ', 21),
('Ekanayaka Stores', 'Mahiyanganaya Road, Theldeniya ', 21),
('Ekmo Eght super', 'Main Street , Medawala', 16),
('Elbert And Silva', 'Panvila Road Wathegama ', 17),
('Electrical and Electronics', 'No 57 Kadugannawa Road , Gampola', 8),
('Electronic and Electrical', 'No 57 Kadugannawa Road, Kandy', 8),
('ELEGANT TOOL MART', 'No 269/3, Watadeniya Road , Hapugahayatathenna, Handessa', 22),
('Elite Hardware', 'Colombo Street ,, Kandy Town', 13),
('Eranda Electronic', 'Kandy Road, Bothalapitiya , Gampola', 8),
('Eranda Electronic', 'Kandy Road, Bothalapitiya , Gampola', 8),
('Eshwaean Multy Shop', 'Kothmale Road, Nawalapitiya ', 19),
('Estate Suppliers', 'No 49 Colombo Street, Kandy', 8),
('Estate Supplies Agency', 'No 08  Gampola Road, Nawalapitiya', 19),
('Ethagala Electrical', 'No 840/3/A Nawalapitiya Road, Ethagala, Gampola ', 19),
('Excellent Oil Mart', 'Colombo Raod, kiribathkubura ', 15),
('F M MULTY CENTER', 'No 13/8, New Town , Digana ', 14),
('F.S Grocery', 'Nuwaraeliya Road, delpitiya ', 24),
('F.T.C FAMILY TRADE CENTER', 'No 55, Dolosbage Road , Nawalapitiya ', 19),
('Faizal Stores', 'Mariyawaththa, Gampola', 8),
('Falcan auto mart', 'No 79/7 Thalathuoya Road , Ampitiya', 25),
('Falcon Hardware', 'No 38/A Kandy Road, Kadugannawa', 12),
('Familly mart', 'No 279/1 IDAMPITIYA Junction , wathurakubura ', 12),
('Family Mart', 'No 62/A Yakgahapitiya , Gunnepana ', 6),
('Family Mart', 'No 62/A Yakgahapitiya , Gunnepana ', 6),
('Family Super center', 'Kuruduwatha Road, Kandy ', 19),
('Fancy cominication', 'Main Street , Wellamboda ', 9),
('Fancy Coner', 'Station Road, Gelioya', 9),
('Fancy Coner', 'Station Road, Gelioya', 9),
('Fancy Kindom', 'No 14 Hewaheta Road, Delthota', 7),
('Fancy Mahal', 'No 55 colombo Street , Kandy ', 13),
('Fancy Mahal', 'Colombo Street', 13),
('Fancy mahal Electronic', 'No 27 Gampola Raod , nawalapitiya ', 19),
('Fancy Stores', 'No 16 king  street  , Kandy ', 13),
('FANCY TIGER', 'Kandy Road , Kadugannawa ', 12),
('Farm Hill Construction', 'Aniwatta', 13),
('Fashion Modification', 'No 17/3 New Town , Digana', 14),
('Fashion Modifications B', 'No J 2007, New Town , Digana ', 14),
('Fathima Trade Center', 'No 423 Nuwaraeliya Road, Pussellawa', 24),
('Fatima Trade Center', 'No 425 Nuwaraeliya Road , Pusellawa, Pussellawa', 24),
('Fazeena Moter Stores', 'No 182 D.S senanayaka Street , Kandy ', 13),
('Fernando Hardware', 'No 72/B Kandy Road, Wathegama ', 17),
('Final Touch Electrical', 'Nawalapitiya Road, Gampola ', 8),
('Fitring asia', 'Kandy Road, Wellamboda', 9),
('Freedom', 'No 15, Hewaheta Road , Rikillagaskada ', 11),
('Fresh and More Store', 'Nawalapitiya Road , Mariyawaththa ', 8),
('Fresh And More Super', 'Nawalapitya Road, Mariyawaththa ', 8),
('Fresh Super', 'no 305, Peradeniya Road, Kandy ', 13),
('Friends Hardware', 'Medawala Road , Gonigoda ', 16),
('G L Stores and Grocery', 'No 320/A Colombo Road , Peradeniya', 15),
('G.K.G Ayuredha Osuhala', 'No 14 Kothmale Road, Nawalapitiya', 19),
('G.S.P super', 'Nuwaraeliya Road , Gampola ', 8),
('G.W.H Hardware', 'New Town , Digana ', 14),
('Gabeshan Store', 'Main Street, Thalathuoya', 25),
('Gagewaththa Stores', 'No 17 Pujapitiya Road, Ambathenna ', 5),
('Galaha Moters', 'Delthota Road, Galaha', 7),
('Gamabayaka Super', 'Kandy Road, Agunawala', 9),
('Gamage Hardware', '111/A Nuwaraeliya Road , Paradeka , Paradeka', 24),
('Gamini Hardware', 'No 27 Kurunegala Road, Aladeniya', 27),
('Gamini Hardware', 'No 13 Thalathuoya Road, Ampitiya ', 25),
('Gamini Traders', 'No 13 Thalathuoya Road , Ampitiya', 25),
('Gampola Electrical', 'Kandy Road, Gampola', 8),
('Ganegoda Moters', 'No 162/2 Marassana Road, Thalathuoya ', 25),
('GANGA COMMUNICATION', 'Alawathugoda Road , Pujapitiya ', 5),
('Ganga Moters', 'Sirimalwaththa Raod, Madawala', 17),
('Ganga Stores', 'Matale Road, Akurana ', 4),
('Gas stores', 'No 17 Hewaheta Road, Delthota', 7),
('Gayan Hardware', 'No 04 New Town , Digana ', 14),
('Gayasri Hardware', 'Kirimetiya Road , Manikhinna ', 6),
('Gelioya Electrical', 'No 23 Kandy Road, Gelioya ', 9),
('General Hardware', 'No 212/A Gelioya Road, Daulagala ', 22),
('Gift House', 'No 13/4 New Town , Digana', 14),
('Gift House', 'No 08 Main street , Galaha', 7),
('Gift Point', 'Kandy Road Gelioya , Gelioya ', 9),
('Gift Selection', 'No 127v Kandy Road, Daulagala', 22),
('Gihan Stores', 'no 262 Kuda Rathwaththa Road, Kandy', 13),
('Global Holdings and Motors', 'No 8 Public Marcket , Delthota', 7),
('Globle Hardware', 'No 38 Colombo Road, Kadugannaes', 12),
('Golden Steel', 'Willium Gopallawa Road , Kandy ', 13),
('Golden Tiger store', 'Kandy Road, Kadugannawa', 12),
('Good Luck Book Shop', 'Main Street , Pojapitiya ', 5),
('Good luck celliluler', 'Centrel Market, Delthota', 7),
('Green Legacy Hardware', 'No 153, Hewaheta Road , Thalwatta', 26),
('Green Super', 'Main Street , Danthure', 12),
('Gulam Store', 'No 2 Aladeniya , Muruthalawa', 27),
('Gunararathna Moters', 'Main Street, Thalathuoya', 25),
('Gunarathana Stores', 'Doragamuwa Road, Doragamuwa ', 20),
('Gunarathna Hardware', 'Main Street, Thalathuoya', 25),
('Gunawaradana Electrical', 'Danthure Road , Pilimathalawa ', 15),
('Gunawaradana Moters', 'Madawala Road, Katugasthota ', 10),
('Gunawaradana Moters', 'Madawala Road, Katugasthota ', 10),
('Gunawaradana Super Mart', 'No 18 Main street , Danthure', 12),
('Gunawaradana Tools Center', 'No 200/2 Pallekela Bazar , Kengalla ', 18),
('Gunawardana Electrical', 'Danthure Road, Pilimathalawa', 15),
('Gunawardana Moters', 'No 309, Godamuduna, Muruthalawa ', 23),
('Gunawardana Super center', 'No 562, Poththapitiya Road, Danthure', 12),
('Guru Traders', 'No 547 Nuwaraeliya Road, Pussellawa ', 24),
('GuruTraders', 'Nuwaraeliya Road , Pussellawa', 24),
('GW CORPORATION (PVT) LTD', 'No 35, Ragala Road , Rikillagaskada ', 11),
('H.A.R Stores', 'No 555 Nuwara Eliya Road, Pussellawa ', 24),
('H.B.M Traders', 'Elugoda Peradeniya, Penideniya ', 22),
('H.G.J Priyaraththa Super', 'Haguranketha Road, Mailapitiya ', 18),
('H.M.G Stores', 'No 330/1 Maligathenna , Gurudeniya', 18),
('H.M.H Stores', 'Manikhinna Road, Sirimalwaththa ', 6),
('H.N.S Hardware', 'No 20/1 Dikirimadawala , Natharanpotha', 26),
('H.N.S Hardware', 'No 20, Deekirimadawala, Natharanpotha ', 6),
('H.S Moters', 'No 14 2/B Natharanpotha , Kundasale ', 26),
('H.S Store', 'Kurunegala Road, Kandy', 27),
('H.T.H Hardware', 'No 308, Mathale Road , Alawathugoda ', 4),
('Hanifa Stores', 'Kalugamuwa Road , Gelioya', 9),
('Hanthana Hardware', 'No 35, 02 Mile Post, Hanthana ', 13),
('Hanthana Hardware', 'No 35, 02 Mile Post, Hanthana ', 13),
('Happy Land Hardware', 'Hedeniya Road, Medawala', 16),
('Harish Mini Mart', ' No 432 Nuwaraeliya  Road, Pussellawa', 24),
('Hashini Hardware', 'No 46, Kudaoya, Pilimathalawa ', 12),
('Hasim Stores', 'Doragamuwa Road, Udathalawinna ', 20),
('Hasim Stores', 'Doragamuwa Road, Udathalawinna ', 20),
('Hasitha Hardware', 'No 133 Doluwa Raod , Kalugamuwa', 7),
('Hedeniya Parmecy and Grocery', 'No 196 Kurunegala Road, Hedeniya', 27),
('Hedinya Parmacy', 'No 196 Kurunegala Road, Werellagama ', 27),
('Hemal Moters', 'No 80, Kothmale Road , Nawalapitiya ', 19),
('Herath Store', 'No 45 Alwathugoda, Alwathugoda, Alawathugoda', 4),
('Herath Stores', 'Kandy  Road, Outhota ', 21),
('Herath weladasela', 'Daulagala , Handessa', 22),
('HESHAN ELECTRICAL', 'No 336/ 2/ C, Golf Ground Road , Digana ', 14),
('HGJ Priyarathna Stores', 'Adikarigama Road , Haguranketha ', 11),
('Hilton Hardware', '5th Mile Post Mathale Road , Akurana', 4),
('Hiru Trade Center', 'No 49/1 colombo Road, Kiribathkubura ', 15),
('Hiru Trade Center', 'No 49/1 colombo Road, Kiribathkubura ', 15),
('Hiruni Grocery', 'No 123/A New Town , Gurudeniya', 18),
('Hirusha Hardware', 'Thotadeniya , Handessa', 22),
('Hirushi Grocery', 'No 112, Gonigoda , Medawala ', 16),
('Hit Power', 'Kandy Road , Rikillagaskada', 11),
('Home Center', 'No 45, Kotmale Road, Nawalapitiya ', 19),
('Huluganga Hydro Power', 'Hulugaga , Hulugaga ', 17),
('Hyrex Hardware', 'No 49 Kandy Road, Madawala', 17),
('I .N .A Book Shop', 'No 313 Kandy Road, Bothalapitiya', 8),
('I.R.M Tools and Spares', 'Kandy Road, Gampola', 8),
('I.S Electrical', '10/1 maint street , pujapitiya ', 5),
('Ibdira Holdin', 'Kandy Road , Rikillagaskada', 11),
('Ideal Bookshop', 'Colombo Street, Kandy', 13),
('Iirfan Hardware and Electrical', 'Udathalavinna , Madige ', 20),
('Iirfan Hardware and Electrical', 'Udathalavinna , Madige ', 20),
('Ilukpitiya Stores', 'No 118 B, Natharanpotha , Kundasale ', 26),
('Imalka Hardware', 'No 187/1, Galaluwa, Manikhinna ', 6),
('Imalsha Hardware', 'No 196/9/6 Suriyagoda Juction , Bulumulla , Kiribathgoda', 12),
('Indika Moters', 'Kandy Road , Digana (Mahaweli Ground) ', 14),
('Indika Moters', 'No 48, Gampola Road , Gelioya ', 9),
('Indika Moters', '02 nd Lane, Nawalapitiya Road , Gampola ', 8),
('INDIKA MOTORS AND TRANSPORT ( PVT) LTD', 'No 964/6 Nilagama, Digana Rajawella, VAT NO 107916415 - 7000', 14),
('Indika Stores', 'No 40 Rikillagaskada Road, Rikillagaskada, Rikillagaskada', 11),
('Indrani Athanayaka Hardware', 'Rikillagaskada Road, Haguranketha ', 11),
('Indunil Hardware', 'No 31, Dharmashoka Mawatha , Kandy ', 6),
('Induwara Construction', 'Ampitiya Road, Thalathuoya', 25),
('Induwara Hardware', 'No 262 Gampola Road, Gelioya ', 9),
('Induwara Hardware', 'No 78, Thalathuoya Road , Ampitiya ', 25),
('Intell Electronic', 'Kandy Road, Rokillagaskada ', 11),
('Intell Electronic', 'Kandy Road, Rokillagaskada ', 11),
('Iresha Book shop', 'Kothamale Road , Nawalapitiya', 19),
('Iresha Hardware', 'Colombo Street , Kandy ', 13),
('Ishara Hardware', 'Kulugammana Junction, Kulugammana ', 27),
('Ishara Hardware', 'no-88 Kulugamana., kandy, kansy', 10),
('Ishara Stores', 'Mahiyanganaya Road , Theldeniya ', 21),
('Ismale Sotres', 'Doragamuwa Road, Doragamuwa ', 20),
('Ismale Sotres', 'Doragamuwa Road, Doragamuwa ', 20),
('Isuraka Auto Parts', 'No 32, Economics Center , Theldeniya ', 21),
('Isuru Enterprises', 'Bopitiya Road , Delthota ', 7),
('Isuru Hardware', 'Haragama Road, Gurudeniya ', 18),
('Isuru Hardware', 'Daulagala Road, Handessa ', 22),
('ISURU SHOPPING CENTER', 'New Town , Digana ', 14),
('Italian Shed', 'No 164 Mathale Road, Kudugala , Akurana', 4),
('Ivoli Furniture', 'No 664 Nuwaraeliya Road, Pussellawa ', 24),
('J.H.S Janahitha Stores', 'No 105 Busstad , Galaha ', 7),
('J.K Moters', 'No 397, Ampitiya Road , Kandy ', 25),
('J.M Stores', 'No 49 Natharanpotha , Kunadasale ', 26),
('J.M.J Grocery', 'No 194 Colombo Street , Kandy ', 13),
('J.R Stores', 'No 14 Old Mathale Road, Alawathugoda', 4),
('J.R Stores', 'No 14 Old Mathale Road, Alawathugoda', 4),
('J.S super', 'Kandy Road, Wathegama ', 17),
('J.S.B Oil Mart', 'No 17 Balagolla , Kengalla', 14),
('Jacket Kingdom', 'No 05/2, Hyth Land, Deltota', 7),
('Jaffna Super', 'Kandy Road, Galaha', 7),
('Jagath Stores', 'No 638, Senarathgama, Katugasthota ', 27),
('Janaka Stores', 'Rikillagaskada Road, Haguranketha ', 11),
('Janaka Stores', 'Rikillagaskada Road, Haguranketha ', 11),
('Janaka Stores', 'Kiuldiya Road, Puliyadda ', 25),
('Janaka Traders', 'No medapitithenna , Haguranketha', 11),
('Janalanka Hardware', 'Kurunegala Road, Hedeniya', 27),
('Janalanka Hardware', 'No 36 Nuwaraelaiya Road , Atabage , Atabage ', 24),
('Janatha Communication', 'No 392/A Kandy Road, Gampola', 8),
('Janatha Hardware', 'No 34 Kandy Road, Gampola', 8),
('Janatha Hardware', 'No 615 colombo road, Illukwaththa ', 12),
('Janatha Hardware', 'No 615 colombo road, Illukwaththa ', 12),
('Janatha Hardware', 'No 457 4 mile post , Katugasthota ', 27),
('Janatha Moters Engeering', 'No 27A Kalapuraya , Natharanpotha', 26),
('Janatha Moters Engeering', 'No 27A Kalapuraya , Natharanpotha', 26),
('Japan Auto Mart', 'No 169, Kandy Road , Kahatapiya, Gampola ', 8),
('Japan Lanka Moters', 'No 20/14 Gampola Road , Gelioya ', 9),
('Jaya Lanka Glass Hardware', 'No 324/3 Kurunegala Raod, Hedeniya ', 27),
('Jayabarathi Store', 'No 43 Old Mathale Road, Alwathugoda, Alwathugoda', 4),
('Jayaboomi Hardware', 'No 84/A Gampola Road, Koshinna', 9),
('Jayakodi Stores', 'Galatha Road, Delpitiya', 24),
('Jayalanka Hardware', 'No 138 Delpitiya, Atabage, Gampola ', 24),
('Jayalanka Hardware', 'mahiyanganaya Road, Oruthotab', 21),
('Jayalanka Hardware', 'No 102  5 th Mile Post, Aladeniya', 27),
('Jayalanka Hardware', 'No 291, Jayamalapura, Gampola ', 19),
('Jayalasindu Hardware', 'Rikillagaskada Road, Perawanguwa', 11),
('Jayalasindu Stores', 'Perawanguwa, hanguranketha ', 15),
('Jayalasindu Stores', 'Perawanguwa, hanguranketha ', 15),
('Jayantha Moters', 'kande Handiya, Unuvinna', 11),
('Jayanthi Stores', 'No 324/20 9th mile post Galoya, hindagala ', 7),
('Jayapathi Hardware', 'kandy Road, Theldeniya', 21),
('Jayapura Trading Company', 'No 11/1 Nawalapitiya Road, Gampola', 8),
('Jayarani Super', 'Daulagala Road, Handessa ', 22),
('Jayarathna Hardware', 'No C /D Pujapitiya Road, Dolopihilla', 5),
('Jayarathna Hardware', 'Daulagala Road, Pamunuwa ', 15),
('Jayarathna Stores', 'No 96 kandy Road, KADUGANNAWA', 12),
('Jayarathna Stores', 'No 96 kandy Road, KADUGANNAWA', 12),
('Jayarathna Stores', 'No 72 Muruthalawa Road, Aladeniya', 27),
('Jayarathna Stores', 'No 96 Kandy Road, Kadugannawa', 12),
('Jayasanda Stores', 'Main streey , Bokkawala', 16),
('Jayashakthi Trade Center', 'No 7 B Digana Road , KundSale , 0758896901', 26),
('Jayashigha Grocery', 'No 424, Kandy Road , Kadugannawa ', 12),
('Jayasinghe Super', 'No 19/A, Madawala rd, Polgolla, Madawala', 17),
('Jayasinha Super', 'No-14 Gonigoda , Medawala, Harispathuwa', 16),
('Jayasiri Hardware', 'No - 14 Ragala Road , Haguranketha', 11),
('Jayasiri Hardware', 'No 17 Ragala Road, Haguranketha', 11),
('Jayasiri Stores', 'No 51 Old Mathale Road, Alawathugoda ', 4),
('Jayathuga Moters', 'Madapitithenna, Haguranketha ', 11),
('Jayawaradana Tea Stores', 'Pichchamalwaththa Junction , Gurudeniya', 18),
('Jayawardaba Hardware', 'No 09/1 Mahaweli Niwasa , Hirrassagala ', 13),
('JDS stores', 'No 23 Old Mathale Road , , Alawathugoda, Alawathugoda', 4),
('Jega Hardware', 'Kanda Junction , Unuwinna', 11),
('Jhothi Store', 'No 64 Nuwaraeliya Road , Atabage, Atabage ', 24),
('Jinnah Hardware', 'Kandy Road, Gampola', 8),
('Jinnah Tools', 'Kandy Road, Gampola', 8),
('Junction Stores', 'Madawala Bazar, Madawala', 17),
('Junction Trade Center', 'Poththapitiya Road, Danthure', 12),
('K.A Dinapala and Sons', 'No 65 Rajaweediya , Kandy', 13),
('K.A.D Moters', 'No 129 B, Digana Road , Kundasale ', 26),
('K.B.K Pasatha Hardware', 'Rikillgaskada Road, Mailapitiya', 11),
('K.B.K Pasatha Hardware', 'Rikillgaskada Road, Mailapitiya', 11),
('K.G.K Stores', 'No 85 Pallewel, Gampola', 8),
('K.G.K Stores', 'No 85 Pallewel, Gampola', 8),
('K.H Moters', 'Kurunegala Road, Werellagama', 27),
('K.H Moters', 'Kurunegala Road, Werellagama', 27),
('K.H.S Moters', 'No 58/A Gampola Road, Peradeniya ', 23),
('K.H.S Moters', 'No 58/A Gampola Road, Peradeniya ', 23),
('K.K .W Traders', 'No 228 Mowbrey Road , Hindagala, Mahakanda', 7),
('K.N Moters', 'Mahiyanganaya Road, Theldeniya ', 21),
('K.P.D Oil Mart', 'No 100 Theledeniya Road, Manikhinna ', 6),
('K.S Book Shop', 'No-07 Medawala, Harispathuwa, Harispathuwa', 16),
('K.S. Stores', 'No 2/2, Rekawalpola, Welamboda', 9),
('K.S.K Stores', 'Main Street , Thalathuoya ', 25),
('K.S.M Hardware', 'No95 Alapolawaththa , Gurudeniya ', 18),
('K.S.S Super Marcket', 'No 201 Kothmale Road , Nawalapitiya', 19),
('K.V.S Hardware', 'No 212 A Pallemulla, Halloluwa', 10),
('KAANDULA Modern Homes Pvt Ltd', 'Ragala Road , Haguranketha ', 11),
('Kadurata Battry Centre', 'Raja Mawatha , Kandenandiya', 11),
('Kadurata Super', 'Theldeniya ', 21),
('Kadurata Super', 'Wilamuna , Theldeniya ', 21),
('Kadurata Tea And product', 'Willamuna ', 21),
('Kalai Moters', 'Dekinda Road , Bawwagama', 19),
('Kalana Hardware', '133/A Gannoruwa , Peradeniya, Peradeniya', 23),
('Kalani Electrical', 'No 35  Padiyapellella Road, Rikillagaskada, Rikillagaskada', 11),
('Kalhara Stotres', 'Kiuldiyaroad, Puliyadda ', 25),
('kalutara Stores', 'No 153Georgende silva Mawatha , Kandyv', 13),
('Kalyani Electrical', 'no 17 Ragala Road, Rikillagaskada ', 11),
('Kalyani Store', 'No 95 Main Street , Galaha', 7),
('Kalyani Stores', 'Wariyagala , Nilambe ', 7),
('Kandurata Hardware', 'No 544, Nuwara Eliya Road , Pussellawa ', 24),
('Kandy Aluminum', 'No 250, Colombo Road , Kiribathkubura ', 15),
('Kandy Auto Spares', 'No 151 C, Thalathuoya Road , Meddepathana, Ampitiya ', 25),
('kandy electrical', 'no 25 ranawana road , katugasthota, katugasthoata', 10),
('Kandy Glass Electrical', 'No 446 Kurunegala Road , Aladeniya', 27),
('kandy Hardware(pvt)ltd', 'D.S Senayakayaka Road, Kandy', 13),
('Kandy Lighting', 'No 81/A Katugasthota Road, Kandy', 13),
('Kandy Roofing (pvt)Ltd', 'Madawala Road , Katugasthota , Katugasthota ', 10),
('Kandy Roofing (pvt)Ltd', 'No 334 Madawala Road , Katugasthota', 10),
('Kandy Steel (PVT) ltd', 'Kurunegala Road, Katugasthota ', 10),
('Kanjani Stores', 'Rikillagaskada Road, Gurudeniya ', 18),
('Kapukotuwa Stores', 'Barigama Road , Barigama, Barigama', 10),
('Karadagolla Hardware', 'Ragala Road , Rikillagaskada ', 11),
('Kavin Ceremic', 'No 141, Kurunegala Road , Katugathota ', 10),
('Keshawa Hardware', 'Thalawakela Road , Nawalapitiya', 19),
('Kings Electrical', 'no 538 kandy Road, Illukwatha', 12),
('Kirthi Stores', 'No-56 Pattiyawaththa, Pattiyawaththa, Pattiyawatha', 16),
('Kirula Hardware', 'Madolkela Road, wathegema', 17),
('Kiyas Stores', 'No 178, Nawalapitiya Road , Ulapane ', 19),
('Kodithuwakku Arrachi Stores', 'Ma oya , Haguranketha', 11),
('KoolTech Electrical', 'No 188 Cross Street , Kandy', 13),
('Kovika Grocery', 'No 446 Nuwaraeliya Road, Pusellawa', 24),
('Krishan Moters', 'Ranawana Road, Katugasthota ', 10),
('Krishna Bajaj', 'No 394 Nuwaraeliya Road, Pussellawa', 24),
('Kulathunga Stores', 'Muruthalawa Road, Ganniruwa', 23),
('Kumara Moters', 'No 01 Keerapane, Gampola ', 8),
('Kumara Stores', '156/A Kurunegala Road, Hedeniya ', 27),
('Kumara Stores', 'No 156/A Kurunegala Road , Hedeniya , Werellagama ', 12),
('Kushan Hardware', 'No 465 Polgasdeniya , Katugasthota', 27),
('Kushan Hardware', 'No 84/1, Senarathgama , Katugasthota ', 27),
('Kusumalatha Stores', 'Bothapitiya, Gampola', 8),
('Kuwait Bajaj Motors', 'No 167, Kandy Road , Gampola ', 8),
('Kwik Fit Moters', 'No-195/C , 6th Mile Post, Madawala, Madawala', 17),
('L R and Sons Electrical', 'No 19 Ranawana Road, Katugasthota ', 10),
('L.M.A Store', 'No 433 Wathuwala  , Katugasthota', 27),
('Laba kade', 'Danthure Road , Pilimathalawa ', 15),
('Lackmini Enterprises', 'No 427, Gallgediyawa, Gampola ', 8),
('Lahiru Multy Center', 'Main Street , Pujapitiya', 5),
('Lahiru Stores', 'Bus Stand No 172/1 Bokkawala, Bokkawala', 16),
('Lahiru Traders', 'Dibulkubura Road , Rikillagaskads', 11),
('Lakbima Moters', 'Golf Road, Digana ', 14),
('Lakbima Moters', 'Golf Road, Digana ', 14),
('Lakbima Stores', 'No 91 Nuwaraeliya Road , Paradeka, Paradeka', 24),
('Lakjaya Hardware', 'kahawaththa Road, Gampola waththa', 8),
('Lakjaya Hardware', 'kahawaththa Road, Gampola waththa', 8),
('Lakjaya Hardware', 'No 164 Katugasthota Road, Halloluwa', 10),
('Lakmali Supercenter', 'Boyagane Road , Elugoda', 22),
('Lakmini Hardware', 'No 4 Nuwaraeliya Road, Pussellawa', 7),
('Laksahana Moters', 'Colombo Road, peradeniya', 15),
('Laksavi Hardware', 'No 55A/2  Aluthgama Jambugahapitiya', 20),
('lakshab Moters', 'Kothmale Road, Nawalapitiya ', 19),
('lakshan Moters', 'Kothmale Road, Nawalapitiya ', 19),
('Lakshan Traders', 'Natharapotha , Natharanpotha ', 26),
('Lakshan Traders', 'Natharapotha , Natharanpotha ', 26),
('Lakshitha Hardware', 'No 194/1, Ranawana, Katugathota ', 16),
('Lakshitha Stores', 'Sarasavi Store', 20),
('Laksiri Hardware', 'No 4 Nuwaraeliya Road, Pusellwlawa, Pussellawa', 24),
('Laksiri Hardware', 'No 4 Nuwaraeliya Road , Pussellawa', 24),
('Lalitha Trade Center', 'No 456 Nuwaraeliya Road , Pussellawa', 24),
('Lanka Electrical', 'No 166 Colombo Street , Kandy', 13),
('Lanka Electrical', 'no 906/28 New Town , Digana ', 14),
('Lanka Hardware', 'No 37, Ranawana Road , Katugathota ', 10),
('Lanka Hardware', 'Main street , Wellamboda ', 9),
('Lanka Hardware', 'No 135, Ambakote, Kengalla ', 14),
('Lanka Steel', 'No 10 Colombo Street , Kandyc', 13),
('Lanka Steel', 'No 99B Waththegama Road, , Madawala Bazar, Madawala', 17),
('Lanka Store', 'No 25 Old Mathale Road, Alawathugoda', 4),
('Lanka Traders', 'Polgollawaththa , restherrow building, Polgolla', 17),
('Lankan Moters', 'Kandy Road , Kadugannawa ', 12),
('Last Chance', 'No 351 Colombo Road, Kehelwala , Pilimathalawa', 15),
('Last Chance', 'No 351 Colombo Road, Kehelwala , Pilimathalawa', 15),
('Lateef Store', 'No 404 Kurunegala Road, Kandy', 27),
('Latha Hardware', 'No 2 A Paper Garden , Pallekeka ', 14),
('Latha Hardware', 'No 2A, Pepper Garden, Pallekelle, Kundasale ', 26),
('Lavish Electrical', 'No 658 /1 Mathale Road, Akurana ', 4),
('Laxman Hardware', 'No 535 Poththapitiya Road, Danthure', 12),
('Laxman Hardware', 'No 181, New Gurudeniya Road , Thennakubura ', 18),
('Laxmi Grocery', 'No  157 Kurunegala Road, Werellagama', 27),
('Laxmi Stores', 'No 122 New Town, Digana', 13),
('Laxmi Stores', 'Kurunegala Road , Werellagama ', 27),
('Liberty Hardware', 'No 17 kandy Road, Gelioya ', 9),
('Life Care Mobile', 'No 530 Nuwaraeliya Road, Pussellawa', 24),
('Life Care Mobile', 'No 530 Nuwara Eliya Road , Pussellawa', 24),
('Light Broght', 'No -C 20 Market , Pussellawa, Pussellawa', 24),
('Light House', 'D.S Senanayaka street , Kandy', 13),
('Lio Electrical', 'No 48/D/4 Colombo Road, Kiribathkubura ', 15),
('Lithu lanka Hardware', 'Watagalathenna, Dolapihilla, Kandy', 5),
('Little Lanka Hardware', 'No 107/1 Willium Goppallawa Road, Kandy ', 13),
('Liyanage Hardware', '12/C, Henwala , Kundasale', 14),
('Liyanage Hardware', 'no 900/1 Nawalapitya Road , Ethgala', 19),
('Liyanage Store', 'Madawala road, Nawayalathenna ', 20),
('Liyanage Store', 'No 266 Madawala Road, Latugasthota', 10),
('Liyanage Store', '87/B Madawala Road , Katugasthota, katugasthota ', 10),
('Liyanage store', 'Madawala Road , Nawayalathenna , katugasthota ', 17),
('Liyanage Stores', 'No 48 B, Meeruppa, Marassana ', 18),
('Liyanage Stores', 'No 63, Waladeniya, Harankahawa', 16),
('Lotus Fancy', 'No 526-Nuwaraeliya Road, Pussellawa, Pussellawa', 24),
('Lucky Hardware', 'No 3 L Aladeniya Road, Muruthalawa', 23),
('Lucky Hardware', 'No 3 L Aladeniya Road, Muruthalawa', 23),
('Luxmi Stores', 'No 122 New Town, Digana', 14),
('M R Hardware and Supplier', 'no-75/1 Barigama, Barigama , Barigama', 10),
('M.B.N stores', 'Thalathuoya Road, Ampitiya', 25),
('M.C Moters', 'No 315 Nuwaraeliya Road, Pussellawa', 24),
('M.D.G.W Tissa Electrical', 'No 114/C, Kandy Road , Paleepana, Poojapitiya ', 5),
('M.G Super center', 'No 97 Kothmale Road , Nawalapitiya', 19),
('M.G. Moters', 'D.S. Senanayaka Street , Kandy', 13),
('M.G.S Grocery', 'Gampola road, Gelioya ', 9),
('M.H.M Hardware', 'No 168, Hedeniya, Werellagama ', 27),
('M.J.H LANKA PRIVATE LIMITED', 'M.J.H Court, No 01, Mawatupola, Alawathugoda ', 4),
('M.K Electronics', 'No 12 Kadugannawa Road, Gampola', 8),
('M.K Electronics', 'No 12 Kadugannawa Road, Gampola', 8),
('M.K Grocery', 'No 572 Polgasdeniya , Katugasthota', 27),
('M.K Stores', 'No 164 Mathale Road, Akurana ', 4),
('M.K. CONCRETE WORKS', 'No 234/C, Wahugapitiya, Pussellawa ', 24),
('M.L Traders', 'No 506 Main Street , Danthure', 12),
('M.M.M Moters', 'No 105, Gangasiri Road , Gampola ', 8),
('M.R.A Treders', 'No 69 Kothmale Road, Nawalapitiya', 19),
('M.R.M Moters', 'No 104, Bopitiya Road , Delthota ', 7),
('M.S Enterprises', 'No45 Pallekele Bazar , kengalla', 14),
('M.S Traders', 'No 96 Diwanawaththa , Batugoda', 5),
('M.T.C Stores', 'No 05 Kandy Road, Kengalla', 14),
('Mackline Communication', 'No 125 Main street , Daulagala', 22),
('Madara Hardware', 'No 17, Meeruppa, Marassana ', 18),
('Madara Stores', 'Batugoda , Pujapitiya ', 5),
('Madara Trade center', 'Main street , Maraasana', 18),
('Madawala Oil Stores', 'Madawala Road , Madawala', 17),
('madige Food center', 'No 32A Udathalawinna, Madawala', 20),
('Madige Food Center', 'No 32A Udathalavinna, Doragamuwa', 20),
('Madina Trade Center', '499/1 Nuwaraeliya Road , Pussellawa', 24),
('Madusanka Auto Works', 'No 656, Kandy Road , Galgediyawa , Gampola ', 8),
('Madushan Enterprises', 'Main Street , Pujapitiya ', 5),
('Maf Family Mart', '621 Road , Natharanpotha', 26),
('Mag city', 'No 14 Nuwaraeliya Street, Gampola', 8),
('Mahagedara Hardware Stores', 'Colombo Road, Ambilmeegama', 15),
('Mahajana Hardware', 'Kuuradeniya Road, Wellamboda', 9),
('Mahajana Hardware', 'No 18, Napana, Manikhinna ', 6),
('Mahajana Stores', 'No 11 Old Mathale Road, Alawathugoda', 4),
('Mahajana super', 'Malabar Street , Gampola', 8),
('Mahajana super', 'Malabar Street , Gampola', 8),
('Mahameuna Asapuwa', 'Kundasale , Kundasale ', 26),
('Mahameuna Asapuwa', 'Kundasale , Kundasale ', 26),
('Mahanama Stores', 'No Nranpanawa Road, Heepitiya Junction , Manikhimma', 6),
('Mahanuwara Hardware', 'Buwelikada Raod , Gelioya ', 9),
('Mahanuwara Moters', 'No 8/5 Nawalapitiya Road , Gampola ', 8),
('Mahanuwara Moters', 'No 459/H Kandy Road, Katugasthota ', 10),
('Mahanuwara Steel', 'No 85 A, Kandy Road , Gelioya ', 9),
('Mahaweli Food Center', 'No 10 New Town , Theldeniya', 21),
('Mahaweli Hardware', 'Wathegama Road , Nawayalathenna ', 17),
('Mahendralal Auto Service', 'No 248, Kahatapitiya, Gampola ', 8),
('Mahesh D Hardware', 'No 20 Gannoruwa, Peradeniya', 23),
('Mahinda Moters', 'Wilamuna, Teldeniya ', 21),
('Mahinda Stores', 'No 69 Sirimalwatha, Gunnepana', 6),
('Makvin Electrical', 'Henawala Kadugannawa', 12),
('Maligathenna Stores', 'No 334/1 Maligathenna , Gurudeniya ', 18),
('Malik Saheed', 'No 02, Katugathota Road , Kandy ', 13),
('Mallika Stores', 'No 144/1, Nawalapitiya Road , Mariyawatta, Gampola ', 19),
('Malwaththa Hardware', 'No 119 Gampola Road, Ulapane ', 19),
('Manathunga Store', '4th Mile Post , Nugewela', 27),
('Manel Stores', 'Luuketiyamadiththa, Menikhinma', 5),
('Manel Trade Center', 'Mathale Road ,, Ambathenna, Katugasthota ', 5),
('Mangala Cominication', 'Kandy Road , Gelioya ', 9),
('Mangala Moters', 'Nuwaraeliya Road, Gampola', 8),
('Mangala Moters', 'Nuwaraeliya Road, Gampola', 8),
('Maniums Stores', 'Nuwaraeliya Road ,Pussellawa , Pussellawa ', 24),
('Manjula Stores', 'Karugasthota  Road, Gohagoda', 10),
('Manjula Stores', 'Karugasthota  Road, Gohagoda', 10),
('Manjula Stores', 'Bolpe, Maraasana', 18),
('Manuja Oil Mart', 'No 84/A/3/1, Siyabalagoda, Danthure ', 12),
('Marhaba Store', 'Hewaheta Road , Delthota', 7),
('Mari Trading', 'Kandagula, Thalathuoya ', 25),
('Mariens Super marcket', 'Kurunegala Road, Senarathgama ', 27),
('Mariens Super marcket', 'Kurunegala Road, Senarathgama ', 27),
('Marimuthu Stores', '03 rd Mile Post , Ampitiya ', 25),
('Marimuthu Stores', '03 rd Mile Post , Ampitiya ', 25),
('Mariyawaththa Grocery Center', 'Mariyawaththa , Gampola', 19),
('Mariyawaththa Grocery Center', 'Mariyawaththa , Gampola', 19),
('Mariyawatta Stores', 'No 2D, Nawalapitiya Road , Mariyawatta , Gampola ', 19),
('Marketing Center', 'Kalugamuwa Road, Gelioya ', 9),
('Marrasana Super', 'No 371/B Pasgama Road, Marrsana', 18),
('Maruthi Hardware', 'No 166 Colombo Street , Kandy', 13),
('Mathale Stores', 'No 15 Main street , Murithalawa', 23),
('Mathi Color center', '24/A/5 Gannoruwa Road, Peradeniya ', 23),
('Mathi Color Cnter', 'No 2 /4 /A/7 Gannoruwa Road, Peradeniya', 5),
('Maweli Store', 'No 532 Nuwaraeliya Road , Pussellawa', 24),
('Max bookshop', 'Doragamuwa Road, Udathalawinna', 20),
('Max Lanka', 'Kuruduwatha Road , Nawalapitiya', 19),
('Max mini Mart', 'No 88/A Willium Gopoallawa Mawatha, Kandy ', 13),
('Mayon Electrical', 'Mahiyanganaya Road, Theldeniya ', 21),
('Mazoomiya HW', 'Main street Akurana, Akurana', 4),
('Meegamana Harware', 'Meegammana Road, Meegamana', 17),
('Meezan Hardware', 'Mathale Road, Ambathenna ', 5),
('Mega Hardware', 'No 11 Kandy Road , Gampola', 8),
('Mega Hardware', 'No 55 Kalapitiya Road, Katugasthota', 10),
('Mega Stores', 'No 16 621 Natharanpotha , Natharanpotga', 26),
('Mega Super', 'Rikillagaskada Road, Gurudeniya ', 18),
('Melbourn Hardware', '1st Mile post , Ambathenna ', 5),
('Methdini Super', 'Kandy Road, Haguranketha ', 11),
('Metro Electrical', 'Station Road, Gelioya ', 9),
('Metro Hardware', 'No 222 A, Dellanga , Gelioya ', 22),
('Metro Traders', 'Kahattapitiya, Gampola ', 8),
('Mini Chips', 'Yatinuwara Lane , Kandy ', 13),
('Mirhaj Auto Vision', 'No 175, Kandy Road , Medawala Bazar', 17),
('Mod Garage', 'Kandy Road, Balagolla ', 14),
('Modern Ceramic House', 'No 104, Bopitiya Road , Deltota', 7),
('Modern Hardwaee', 'No 224 Mathale Road , Akurana, Akurana', 4),
('Modern Hardware', 'No 32, Panabokka Mawatha , Gampola ', 8),
('Modern Lanka Moters', 'No 248, Kandy Road , Kahatapitiya, Gampola ', 8),
('Mohamadiya Stores', 'No 317, Madawala Road , Katugasthota ', 17),
('Mohomadia Hardware', 'Madawala Road, Katugasthota ', 10),
('Molligoda Hardware', 'No 404/A Colombo Road, Pilimathalawa', 15),
('Moni Company', 'Kotugodalla Street , Kandy ', 13),
('Moragiri Oil Mart', 'No 634 F Kurunegala Road, Katugasthota ', 27),
('Moragiri Oil Mart', 'No 634 F Kurunegala Road, Katugasthota ', 27),
('Mount Cresent Hardware', 'No 81 Bowalawaththa , Kandy', 13),
('Mudaliwaththa Stores', 'No 90 Colombo Road, Kadugannawa', 12),
('Multy Choice', 'No 107 Bus stand , Kandy Road, Galaha ', 7),
('Multy Hardware', 'no- Ranawana Road, katugathota, katugasthota', 10),
('Multy Hardware', 'Ranawana Road, Katugasthota ', 10),
('Multy Hardware(Galaha)', 'No 97 Main Street , Galaha', 7),
('Multy Super City', 'No 136  9 Mile Post , Alwathugoda', 4),
('Multy suuply', 'Kurunegala Road, Katugasthota ', 10),
('Multy suuply', 'Kurunegala Road, Katugasthota ', 10),
('Multy Tech Engineering', 'No 42, Soyasakele Road , Nawalapitiya ', 19),
('Multy Trade Center', 'Colombo Raod, Henawala', 12),
('Multy Trade Center', 'Colombo Raod, Henawala', 12),
('Multy Trade center', 'No 490 Hennawala, Kadugannawa', 15),
('Multy Trading', 'No 35 Gampola Road , Gelioya ', 9),
('Muluthenge Stores', '07 Kanuwa, Gelioya ', 9),
('Muthubanda Stores', 'Main street , pujapitiya', 5),
('N.A.S Stores', 'No 96 Nuwaraeliya Road, Paradeka ', 24),
('N.H Moters', 'Kandy Road, Kengalla', 14),
('N.H.S Stores', 'Agunawala , Gelioya ', 9),
('N.H.S Stores', 'Agunawala , Gelioya ', 9),
('N.M Moters', 'no 360/B Pollgollawatha , Polgolla ', 17),
('N.M Moters', 'no 360/B Pollgollawatha , Polgolla ', 17),
('N.M Senanayaka Stores', 'Colombo Street, Kandy', 13),
('N.M Traders', 'no 70 Mathale Road, Akurana', 4),
('N.M Traders', 'No 61 Nuwaraeliya Road, Gampola', 8),
('N.N. Hardware Concrete Words', 'No 57, Bopitiya Road , Delthota ', 7),
('N.R Stores', 'No 371, Halloya, Peradeniya ', 7),
('N.T.S Alluminium', 'Kurunegala Road, Aladeniya ', 27),
('N.T.S Aluminum', 'Kurunegala Road , Aladeniya ', 27),
('Nadan Printers', 'No 08 Kotugodella Street , kandy ', 13),
('Nadeekass stores', 'No 33 Kothmale Road, Nawalapitiya', 19),
('Nadeera Stores', 'Medawala Road , Gonigoda, Gonigoda', 16),
('Nadeesha Hardware', 'No 5 Kurunegala Road, Nugewela', 27),
('Nadeesha Shopping Complex', 'No 264, Colombo Road , Pilimathalawa ', 15),
('Nadeeshan stores', 'No 88 N eliya Road , Paradeka ', 24),
('Nadiwasana Store', 'No -13 Pattiyawaththa, Pattiyawaththa, Pattiyawaththa', 16),
('Nadun Book shop', 'Ehalagashinna, Pojapitiya ', 5),
('Nagolla Stores', 'Nawalapitiya , Ulapane ', 19),
('Najeem Stores', 'Doragamuwa Road, Udathalawinna ', 20),
('Nalaka Bookshop', 'hewaheta Road , Rikillagaskasa', 11),
('Nalaka Hardware', 'No 94, Dimbullkumbura Road , Rikillagaskada ', 11),
('Namal Hardware', 'Hirrassagala Road, Kandy ', 13),
('Namal Pole Kade,', 'No 70/3 Nuwaraeliya Road, Gampola', 8),
('Nanayakkara Stores', 'Diyayabubula , Digana ', 14),
('Nanayakkara Stores', 'No 265, Dullawa, Medawala ', 16),
('Nandana Stores', 'No 412 Nuwaraeliya Road, Pussellawa', 24),
('Nawa Lanka Hardware', 'No 645 Colombo Road, Illukwaththa , Kaduganawa', 12),
('Nawalanka Hardware', 'No 20, Arambekade, Kumburegama', 27),
('Nawarathna Hardware', 'No 227/B hirayapitiya , Handessa ', 22),
('Nawarathna Trade Center', 'Kandy Road, Pilimathalawa ', 15),
('Nayana Store', 'No 09 Main Street , Thalathuoya', 25),
('Nehara Moters', 'No -300/B Nuwaraeliya Road , Pussellawa, Pusselawa', 24),
('Nethmi Book Shop', 'No 17/01, Uyanwattha, Polgolla, Madawala', 17),
('New Mahanuwara Moters', 'No 479 Kurunegala Road , Aladeniya', 27),
('New A.T.S Stores', 'Panvila Road, Wathegama ', 17),
('New Ajmal Brothers', 'Kandy Road , Gelioya ', 9),
('New Al Ameen Moters', '138/A wahugahapitiya, Pussellawa, Pussellawa', 24),
('New Aniwaatte Hardware', 'No 40 a/2, Bahirawakanda Path, Kandy ', 13),
('New Ariya Jewellery and Electrical', 'Main Street , Marassana ', 18),
('New Ariya Jewellery and Electrical', 'Main Street , Marassana ', 18),
('New Asian Hardware', 'No- 131, Wanguwakade, Madawala Bazar, Madawala', 17),
('New Asian Hardware', 'no 315 Kandy Road, Bothalapitiya ', 8),
('New Asian Hardware', 'No 315 Kandy Road , Botalapitiya, Gampola ', 8),
('New Asian Moters', 'No 17 Golf Road , Digana', 14),
('New Bala Hardware', 'No 919/A Matale Road, Alawathugoda ', 4),
('New Bobby Hardware', 'No 19 Kandy Road, Balagolla', 14),
('New Central Hardware', 'No 39 Colombo Street, Kandy', 13),
('New central Moters', 'No459/G Katugasthota Road , Kandy', 10),
('New Central Stores', 'No 188 Colombo Road , Pilimathalawa', 15),
('New Centrel Hardware', 'No 01 Buwanekaba Road, Gampola', 8),
('New Centrel Hardware', 'Colombo Street, Kandy ', 13),
('New Centrel Hardware', 'No-55 Kurunegala Road, Katugasthota , Katugasthota ', 10),
('New Centrel Hardware Stores', 'No 264, Medawala Road , Katugasthota ', 17),
('New City Electrical', 'Victoria Road , Digana ', 14),
('New City Glass Hw', 'No 92/A Kandy Road , Galaha', 7),
('New City Hardware', 'No 71 /A Malabar street, Gampola', 8),
('New City Hardware', 'No 149, Main Street , Hapugastalawa', 19),
('New City Traders', 'no 73 Nuwaraeliya Road, Gampola', 8),
('New Doragamuwa Hardware', 'No 21/A Doragamuwa Road, Polgolla', 20),
('New Fancy Mahal', 'No 78, Colombo Street , Kandy ', 13),
('New Fancy Mahal', 'No 02, Kothmale Road , Nawalapitiya ', 19),
('NEW GLASS HOUSE / HARDWARE', 'No 34 , Kothmale Road , Nawalapitiya ', 19),
('New Golden Hardware', 'No 494 , Colombo Road , Henawela , Kadugannawa ', 12),
('New Golden Steel', 'Vikalpa Mawatha, Pujapitiya', 5),
('New Golden Steel', 'No No 72 1/B Vikalpa Mawaththa , Pujapitiya', 5),
('New Hanifa Stores', 'No 07 station Road , Gelioya ', 9),
('New Hiland Stores', 'Kandy Road , Kadugannawa ', 12),
('New Janatha Traders', 'No 01, Old Mathale Road , Alawathugoda ', 4),
('New Kandy Hardware and Paint houses', 'No 288 Kandy Road , Kadugannawa ', 12),
('New Lanka Aluminum', 'No 370/2, Colombo Road , Pilimathalawa ', 15),
('New Lanka Hardware', 'Vikalpa Mawatha , Pujapitiya, Pujapitiya', 5),
('New Lanka Steel', 'No 10 Colombo Street , Kandy ', 13),
('New Last Chance', 'No 351 ,Colombo Road , Kiribathkubura', 15),
('New Luccky Hardware', 'No 213 Matale Road , Akurana , Akurana', 4),
('New Lucky Stores', 'No 389 Nuwaraeliya Road, Pussellawa', 24),
('New Mahaweli Stores', 'No 35/ 1 Madawala Road , Madawala', 17),
('New Multy Hardware', 'Kandy Road , Daulagala ', 22),
('New Multy Traders', 'No 2 Nuwaraeliya Road , Pussellawa, Pusellawa', 24),
('New Priya Stores', 'No 125 D.S senanayaka Street , Kandy ', 13),
('New Rajapihilla Hardware', 'No 122 Ampitiya Road, Rajapihilla', 25),
('New Rajapihilla Traders', 'No 211 Rajapihilla Mawatha, Kandy', 25),
('New Rathnayaka Hardware', 'Pilimathalawa Road, Daulagala', 22),
('New S.R Hardware', 'No 11 Ampitiya Road , Kandy', 25),
('New Sajidas Hardware', 'No 327 Bothalapitiya, Gampola', 8),
('New Samagi Store', 'No 4/B Doranegama Road , Medawala, Harispathuwa', 16),
('New Samagi Traders', 'Main  Street Medawala, Medawala', 27),
('New Singhe Stores', 'No 05, New Town , Karalliyadda, Teldeniya', 21),
('New Siri Irion Work', 'Kandy Road, Batawaththa', 25),
('New Siri Irion Work', 'Kandy Road, Batawaththa', 25),
('New Star Moters', 'New Town , Digana', 14),
('New Thilakarathna Stores', 'No 51/1, Napana, Menikhinna', 6),
('New Ulammas Pvt Ltd', 'No 63, Kotugodalla Street , Kandy ', 13),
('New Vahini Hardware', 'No 36, Peradeniya Road , Kandy', 13),
('Niaam Moters', 'No 32 Dodakubura Road, katugasthota', 10),
('Nico Grinding Mill', 'No 04, Guhagoda Road , Katugasthota ', 10),
('Nics Electro', 'no 61, sirimalwaththa, gunnepana, kandy', 6),
('Nihal Stores', 'No 549 Main Street , Danthure', 12),
('Nikkoh Lanka Hw', 'No 33 Wahabdeen Complex , Digana, Digana', 14),
('Nilan Store', 'Udathawinna , Madige', 20),
('Nilantha Moters', 'Kandy Road , Pilimathalawa ', 15),
('Nilantha Stores', 'No 27/A Aruppola Road Kandy', 6),
('Nilmini Fancy Palace And text', 'no 108 new town , Digana ', 21),
('Nilupul Grocery', 'No 671 Ballagola , Kengalla ', 14),
('Nimal Stores', 'No 161, Wahupitiya, Pussellawa ', 24),
('Nippn Hardware', 'Dawlagala Road , Thotadeniya ', 22),
('Nippon Center', 'Old Mathale Street , Alwathugoda, Alawathugoda', 4),
('Nippon Electrical', 'No 54, Kotugodalla Street , Kandy ', 13),
('Nipula Stores', 'Galaha Road, Hanthana ', 7),
('Niro Electrical', 'Poththapitiya Road , Danthure', 12),
('Nishantha Moters', '18 Mile Post, Deltota Road , Galaha', 7),
('Niyangoda Hardware', 'No 32 Niyangoda , Kuburegama ', 27),
('Niyarepola Supercenter', 'Dibulkubura Road, Rikillagaskada', 11),
('Nizam and Brothers Stores', 'Madawla Raod, Madawala ', 17),
('Nugesha Hardware', 'No 66 pilawala , Gunnepana', 6),
('Nugesha Hardware', 'No 66 pilawala , Gunnepana', 6),
('Nugewela Bajaj', 'Uyanwaththa , Nugewela', 27),
('Nuwan Electrical', 'Kandy Road, Pilimathalawa ', 15),
('Nuwan Tex Teaders', 'No 86, Aldeniya Road, Muruthalaea', 23),
('Nuwan Trade Center', 'No 100 Agunawala, Peradeniya', 9),
('Nuwarapaksha Stores', 'no 76 Daulagala Road, Daulagala', 15),
('Nuwarapaksha Stores', 'no 76 Daulagala Road, Daulagala', 15),
('Okinawa Stores', 'No74/3 New Digana Road, Kundasae ', 26),
('Omega Electrical', 'No 149 D.S Senanayaka Street , Kandy ', 13),
('Omega Hardware', 'No 61 Kothmale Road, Nwalapitiya', 19),
('Omega Trade Center', 'No 67 Main Street , Thalathuoya', 25),
('Omek Lighting', '20 Mile Post , Kandy Road, Rikillagaskada', 11),
('Omek Lighting', 'Digana Road , Thalwatha', 26),
('OMINDI HARDWARE', 'No 204 D 1, Gannoruwa Road , Muruthalawa ', 23),
('Orbit Hardware', 'Mathale Road , Wathegama', 17),
('Oruthota Traders', 'No 27/4 Theldeniya Road, Oruthota ', 21),
('Oslo Electrical', 'Cross Street , Kandy ', 13),
('Otomo Radiator', 'Katugasthota Road , Kandy ', 10),
('Oxford Electrical', 'No 14 B Victoria Golf Road , Digana ', 14),
('P.K HARDWARE', 'Enamaldeniya Road , Watassa', 22),
('P.K Traders', 'Bus Stand , Haguranketha ', 11),
('P.N Stores', 'No 17 New Town Digana , Digana', 14),
('Pala Stores', 'No 06 , Main Street , Bokkawala ', 16),
('Pala Trade Center', 'Main Street , Nawalapitiya ', 19),
('Pala Trade Center', 'Main Street , Nawalapitiya ', 19),
('Pali Traders', 'No 682 Kandy Road, Kadugannawa', 12),
('Pallemulla Stores', 'No 175, Pallemulla , Halloluwa ', 10),
('Pallewela Hardware', 'No 83/v  pallewela gampola, Gampola ', 7),
('Pallewela Hardware', 'No 94/4  Pallewela, Gampola', 8),
('Pallewela Moters', 'Pallewela , Gampola', 8),
('Paper Line (pvt) Ltd', 'Cross Street , Kandy', 13),
('PAPERLINE OFFICE EQUIPMENT (PVT) LTD', 'NO 10, CROSS  STREET , KANDY, VAT NO 107319387 - 7000', 13),
('PAPERLINE SUPER (PVT) LTD', 'NO 21, CROSS STREET , KANDY, VAT NO 107520473 - 7000', 13),
('PAPERLINE TRADING (PVT) LTD', 'NO 14, CROSS STREET , KANDY, VAT NO 114476420 - 7000', 13),
('Parker Peek Stores', 'Halloya, Hindagolla', 7),
('Pasindu Hardware', 'No 20 Moobro road, Mahakanda ', 7),
('Pasindu Hardware', 'No 20/15 Gampola Road, Gelioya ', 9),
('Pasindu Moters', 'No 77 5th Mile Post , Ambathenna, Ambathenna', 4),
('Pathum Car audio', 'No -120 Mathale Road , Ambathenna', 4),
('Pathum Mothers', 'Theldeniya Road , CTB dipo ', 21),
('Pathum Mothers', 'Theldeniya Road , CTB dipo ', 21),
('Pehesara Stores', 'Hindagala , Haloya', 7),
('Pencils Stores', 'No 72 Hospitel Road, Galaha', 7),
('Peonix Gift House', 'No 1 Gurudeniya Road , Thalathuoya', 25),
('Perera Stores', 'No 153 , Nilamba , Galaha', 7),
('Perera Stores', 'Aruppola road, Aruppola', 6),
('Perera Stores', 'Aruppola road, Aruppola', 6),
('Photo Image', 'Ayuredha Road, Pallekela ', 14),
('Pilimathalawa Trade Center', 'No 284 Colombo Road, Pilimathalawa', 15),
('Podi Kade', 'No 316 , Polgahamula Juction, Peradeniya', 15),
('Pollegolla Hardware', 'No 17 Uyanwatha Road , Pollgolla ', 17),
('pollgolla hw (gas center)', 'pallegunnapana,polgolla', 6),
('pollgolla hw (gas center)', 'pallegunnapana,polgolla', 6),
('Poojitha Hardware', 'No 431, Katugasthota Road , Kandy ', 10),
('Prabhashi Construction', 'No- 2/A Dolapihilla , Pujapitiya', 5),
('Pradeep Hardware, Moters', 'No 103, Unuwinna, Unuwinna', 11),
('Pradeep Moters', 'No 386, Colombo Road , Eriyagama, Peradeniya ', 15),
('Prarthana Moters', ' 08 Kanuwa, Hedeniya , Werellagama ', 27),
('Preddep Moters', 'No 829/4 Mathale Road, Alwathugoda', 4),
('Predeep Moters', 'No 829/4 Mathale Road, Alawathigoda', 4),
('Predeep Store', 'No 73 Sinharapitiya , Gampola', 8),
('Predeep Store', 'No -73 Sinharapitiya , Gampola ', 8),
('Predeep Stores', 'No 06 Janasavigana, kundasale ', 26),
('Predeep Stores', 'No 09 New Town , Kandy ', 18),
('Prem Hardware', 'Gampola Road, Peradeniya ', 9),
('Premarathna Hardware', 'Hindagala, Galoya ', 7),
('Premarathna Stores', '145/1 Anuragama , Gurudeniya ', 18),
('Premarathna Stores', '145/1 Anuragama , Gurudeniya ', 18),
('Premarathna Stores', 'Rajawatta, Bokkawala ', 16),
('Preneeth Hardware', 'No 300 /10 Warathenna, Halloluwa', 10),
('Preneeth Hardware', 'no-300/10 warathenna, Haloluwa, Haloluwa', 10),
('Pressana Hardware', 'Kandy Road , Arawa, Marassana', 18),
('Priya Store', 'Kandy Road, Gampola', 8),
('Priyananda Stores', 'Kandy Road, Thennakubura ', 26),
('Priyananda Stores', 'Kandy Road, Thennakubura ', 26),
('Priyanath Stores', 'no 437 Madawala Road, Nwayalathenna', 20),
('Priyantha Store', 'Kandy Road , Pilimathalawa ', 15),
('Priyarathna Store', 'Main Street , Nawalapitiya ', 19),
('Priyaraththa store', 'Main street , Nawalapitya ', 19),
('Priyaraththa store', 'Main street , Nawalapitya ', 19),
('Propergenda Sales', 'Kandy ', 13),
('Ptebath Construction', 'Udagama , Galhinna', 5),
('Pujapitiya Stores', 'Sisira Main street , Pujapitiya', 5),
('Pujitha Hardware', 'no 164 Kuda Rathwatha Road, Kandy', 5),
('Pussellawa Super Mart', 'Kandy Road, Rikillagaskada ', 11),
('R.I.N Moters', 'Dunuwila Road, Akurana ', 4),
('R.M.S Hardware And Transport', 'no109A Radagaskanda Road, Ampitiya ', 25),
('R.N.A Moters', 'No 31 A Gampola Road , Gelioy ', 9),
('R.S.Auto Trading', 'No 36, Wathegama Road , Madawala ', 17),
('R.S.S Moters', 'No 185/3 Delpitiya, Atabage', 24),
('R.W.D Stores', 'No 72 Sisira Stores, Naranpanawa Road , Manikgihinna', 6),
('Rabdika Hardware', 'No 325/1 Nugewela, Nugewela', 27),
('Rachitha Communication', 'E2 Gurudeniya Road, Thalathuoya', 25),
('Raino Hardware', 'No-10 Kandy Road , wathegama, wathegama', 17),
('Rajakaruna Electrical', 'Main Street , Pujapitiya', 5),
('Rajapaksha Hardware', 'No 87, Godapalawatta Junction, Medawala', 16),
('Rajapaksha Stores', 'No 170 Kurunegala Road, Werellagama', 27),
('Rajapihilla Hardware', 'no-122 Rajapihilla Mawatha, Kandy ', 25),
('Rajapihilla Hardware', 'No 421, Rajapihilla ', 16),
('Rajew Steel', 'No 483/1Madawala Road , Katugasthota', 10),
('Rajini Moters', 'No 29 Galaha Road, Delthota', 7),
('Rajith Store', 'No 16 pattiyawaththa , Rajawella , Rajapihilla', 16),
('Ranashighe Stores', 'No 132, Nuwara Eliya Road , Dellpitiya', 24),
('Ranathunga Stores', 'Senarathgama , Katugasthota ', 27),
('Ranathunga Stores', 'Senarathgama , Katugasthota ', 27),
('Ranaweera Stores', 'Thotadeniya , Handessa ', 22),
('Ranga Store', 'No- 37/2/1 Ranawana Road, Medawala', 16),
('Ranga Stores', 'Doluwa Raod, Hidagala', 7),
('RANJAN TRADERS', 'No 162/1, Kandy Road , Pilimathalawa ', 15),
('Ranjith Aircon / Electrical', 'No 174, Kurunegala Road , Hedeniya ', 27),
('Ranjith Hardware', 'No 49/1 Salgasuyana , New Town , Kundasale', 26),
('Ranjith Hardware', 'No 217, Nawalapitiya Road , Gampola ', 19),
('Ranlo Hardware', 'No 16 3rd Mile Post, Ampitiya', 25),
('Ransel Electrical', 'No 22 Wadugodapitiya veediya, Kandy', 13),
('Ransilu Stores', 'No 64 A, Thalathuoya Road , Ampitiya ', 25),
('Rasanja Grocery', 'Haguranketha Road, Mailapitiya ', 18),
('Rasanjana Grocery', 'No 250/7/2, Kandy Road , Mailapitiya ', 11),
('Rasing Traders', 'J 97 A 11, New Town , Digana ', 14),
('Rathana Hardware', 'No 28/A Kandy Road, Manikhinna', 6),
('Rathna Auto Electrical', 'No 92, Karamada, Gelioya ', 9),
('Rathna Enterprises', 'No 52/2, Aladeniya, Werellagama', 27),
('Rathna Hardware', 'No 821 Matale Road, Alawathugoda', 4),
('Rathna Hardware', 'No 27 A Kandy Road, Manikhinna', 6),
('Rathna Hardware', 'No 821 Mathale Road, Alawathugoda', 4),
('Rathna Hardware', 'Padiyapellella Road, Haguranketha', 11),
('Rathna Stores', 'Gannoruwa , peradeniya ', 23),
('Rathna Stores', 'No 52/1, Aladeniya , Werellagama ', 27),
('Rathna Super', 'Padiyapellella Road, Rikillagaskada ', 11),
('Rathnasiri Stores', 'Kandy Road, Gurudeniya ', 18),
('Rathnayaka Book Shop', 'No 380, Gampola Road , Peradeniya ', 9),
('Rathnayaka Hardware', 'No - 212/5 Ehelagashinna , Kiralagama, Batugoda', 5),
('Rathnayaka Mini Mart', 'Rikillagaskada Road, Maligathenna ', 18),
('Rathnayaka Moters', 'Naththaranpotha , Kundasale ', 26),
('Rathnayaka Moters', 'Naththaranpotha , Kundasale ', 26),
('Rathnayaka Moters', 'Main Street , Bokkawala ', 16),
('Rathnayaka Moters', 'No 199, Kettawala, Ampitiya ', 25),
('Rathnayaka Moters', 'Gampola Road , Gelioya ', 9),
('Rathnayaka Moters', 'Buwanekaba Road , Gampola ', 8),
('Rathnayaka Stores', 'No 83/23/A1, Maligawatta, Daggolla', 13),
('Rathnayaka Stores', 'Main street , Marassana ', 18),
('Rathnayaka Stores', 'Nawalapitiya Road , Ulapane', 19),
('Rathnayaka Stores', 'Nawalapitiya Road , Ulapane', 19),
('Rathnayaka Stores', 'No 83/23/A/1 Dangolla , Maligawatha ', 13),
('Rauf Store', 'No -455, Nuwaraeliya Road , Puseellawa', 24),
('Ravi Traders', 'Madawala Road, Manikhinna ', 6),
('Rayhanayaka Stores', 'Main Street , Pujapitiya ', 16),
('Razak Stores', 'No 21, Kandy Road , Naranwala, Handessa', 22),
('Razy Moters', 'No 50, Kandy Road , Medawala ', 17),
('Red sea Spice Coner', 'No 62 Kandy Road, Kadugannawa ', 12),
('Regal Hardware', 'No 40 Colombo Street, Kandy ', 13),
('Regency Super', 'No 34 Maligathenna , Gurudeniya ', 18),
('Regency Super', 'No 34 Maligathenna , Gurudeniya ', 18),
('Relance Hardware', 'No 63 Katugasthota Road, Kandy ', 13),
('Relax Steel', 'No 10 Marrasana Road, Thalathuoya', 25),
('Relax Steel (Ampitiya)', 'Thalathuoya Road, Ampitiya ', 25),
('Renuka Hardware', 'No 461, Nuwaraeliya Road , Pussellawa ', 24),
('Reto Electrical', 'No - 520/26 Mathale Road, Akurana, Akurana ', 4),
('Rezeen Auto Electrical', 'kaluganuwa Road, Gelioya ', 9),
('Rhythm Booth', 'No 20/15, Gampola Road , Gelioya ', 9),
('Rhythm Car Audio', 'Gampola Road , Weligalla', 9),
('RIDE WAVE MOTORS', 'No 114 j, Palipahana, Pojapitiya ', 5),
('Rithu Enterprises', 'Ranawana Road , Medawala', 16),
('Rizmin Hardware', 'No 5 Public Marcket , Delthota', 7),
('Rohan Stores', 'Kulugammana ', 10),
('Rohans Enterprises', 'No -543 Nuwaraeliya Road, Nuwaraeliya', 24),
('Rohans Hardware', 'No 345, Nuwaraeliya Road , Pussellawa ', 24),
('Royal Hardware', 'No-65/3 Gohagoda Road , Gohagoda, Gohagoda', 10),
('Rubi Glass House', 'No 191, Colombo Road , Pilimathalawa ', 15),
('Ruchira Hardware', 'No 348/2 Golf Road, Digana', 14),
('Rukmal Electrical', 'Kirimetiya Road, Manikhinna ', 6),
('Rukmal Electrical', 'Kirimetiya Road, Manikhinna ', 6),
('Rupasinha Grocery', 'no 6 Ranawana Road, Medawala', 16),
('Ruwan Store', 'No 49/1 Doragamuwa Road, Pollgolla ', 20),
('S S Hardware', 'No 470/3 Gohagoda Road, Katugasthota', 10),
('S M K Electrical Hardware', 'No 397/5E Old Haloya, Nilamba ', 7),
('S T N STORES', 'No 31, Malabar Street , Gampola ', 8),
('S.A.T Hardware', 'Thalathuoya Road, Ampitiya', 25),
('S.G.M Traders', 'No 17 Main Street, Muruthalawa', 23),
('S.H Stores', 'No 98Pussellawa Road, Paradeka ', 24),
('S.H Stores', 'No 98Pussellawa Road, Paradeka ', 24),
('S.H.K Trading', 'Mahiyanganaya Road, Theldeniya', 21),
('S.H.K Trading', 'Mahiyanganaya Road, Theldeniya', 21),
('S.I S Trading', 'Thalawakela Road , Nawalapitiya', 19),
('S.J Hardware', 'No 224 Walala Manikhinna ', 6),
('S.K Hardware', 'No03 Dikirmadawala , Natharanpotha', 26),
('S.K Hardware', 'No03 Dikirmadawala , Natharanpotha', 26),
('S.K.D Auto Mart', 'Buwanekaba Road , Gampola ', 8),
('S.M .K Moters', 'Theldeniya Road , Digana', 14),
('S.M Hradware', 'No 90/A Sarananda Roaf, Penifebiya', 22),
('S.M.J Hardware Pvt ltd', 'Colombo Street , Kandy ', 13),
('S.M.K Amila Stores', 'No 22 B Theldeniya Road, Manikhinna ', 13),
('S.M.K Bajaj Trade Center', 'No 65/5, Mahiyanganaya Road , Old Town , Digana ', 14),
('S.M.R Enterprises', 'No 62 Wilamuma, Theldeniya ', 21),
('S.M.R MOTORS', 'Mahiyanganaya Road , Teldeniya ', 21),
('S.M.R Stores', 'Kandy Road, Kengalla ', 14),
('S.M.W super', 'No - 140 3A Araliya Uyana , Kiribathkura', 15),
('S.N Moters', 'No 115, Kandy Road , Welligalla ', 9),
('S.P.S Moters', 'Colombo Street, Pilimathalawa ', 15),
('S.P.S MOTORS', 'No 290/10, Potawalawatha, Gelioya ', 9),
('S.P.S Stores', 'Henawala, Kadugannawa', 12),
('S.R Traders', 'Thalathuoya Road, Thalathuoya', 25),
('S.S HARDWARE AND PAINT CENTER', 'No 103, Ranawana Road , Katugasthota ', 10),
('S.S stoters', 'No.126, Pahala Dulwala , Halloluwa, Haloluwa', 10),
('S.S.T Stores', 'No15/2 Madawala Road, Nawayalathenna ', 20),
('Sadakelum Moters', 'no-129/1 Uduwawala , Pattiyawaththa, Pattiyawaththa', 16),
('Sadesa Moters', 'No 337, Kandy Road , Gampola ', 8),
('Sadhana Treders', 'Kothamale Road, Nawalapitiya', 19),
('Safna Shoe Palce', 'No 7 Centrel Marcket', 7),
('Sagara Electronics', 'No 101, Agunawela, Peradeniya ', 9),
('Sahana Grocery', 'Ambilmeegama , Pilimathalawa ', 15),
('Sahara Construction', 'Mariyawatta , Gampola ', 8),
('SAHEED', 'Mo 02, Katugasthota Road , Kandy ', 13),
('Saino Moters', 'No 607, Danthure ', 12),
('Sajaniya Bites', 'No 434 Nuwaraeliya Road, Pussellawa', 24),
('Sakura Traders', 'No 03, Aladeniya Road , Muruthalawa ', 23),
('Saleem Hardwaee', 'No 86 Colombo Road, Kadugannawa', 12),
('Saleem Hardware', 'No  86 Colombo Road, Kadugannawa', 12),
('Salinda Moters', 'HAGURANKETHA Road, Haguranketha ', 11),
('Salinda Moters', 'HAGURANKETHA Road, Haguranketha ', 11),
('Salinda Moters', 'Maiyangana Road , Theldeniya ', 21),
('Saliya Stores', 'No 16 Bus stand , Haguranketha ', 11),
('Saliya Stores', 'No 16 Bus stand , Haguranketha ', 11),
('Samagi Auto Movers', 'No 361 B Colombo Road, Peradeniya ', 15),
('Samagi Auto Movers', 'No 361 B Colombo Road, Peradeniya ', 15),
('Samagi Stores', 'Main street , Medawala ', 16),
('Samagi Stores', 'Lewella , Kandy ', 6),
('Saman Communication', 'Gurudeniya Town , Gurudeniya ', 18),
('Saman Hardware', 'Wariyagala , Nillamba ', 7),
('Saman Kumara Hwardware', 'No 100 kandy Road  , Mailapitiya', 11),
('Samanala Book Shop', 'Old Mathale Road, Alawathugoda', 4),
('Samantha Hardware', 'Jayaudana gama', 19),
('Samantha Stores', 'Aruppolawaththa Aruppola, Arupooala', 6),
('Samarakoon Store', 'Nuwaraeliya Road , Pussellawa ', 24),
('Samarakoon Stores', 'No 436 B wiguhumpola , werellagama', 27),
('Samarathunga Hardware', 'No 93 Haguranketha Road, Mailapitiya, Mailapitiya', 11),
('Sambhavi Grocery', 'No 100 Nuwaraeliya Road, Paradeka', 24),
('Sameera Oil / Spare', 'No 22, Nidahas Mawatha , Gampola ', 8),
('Sampath Electrical', 'No 18, Kothmale Road , Nawalapitiya ', 19),
('Sampath Hardware', 'No 282 ,Colombo Road , Kiribathkubura', 15),
('Sampath Hardware', 'Nuwaraeliya Road, Gampola', 8),
('Sampath Hardware', 'No 277/1 Bokkawala Road, Pujapitiya', 5),
('Sampath Hardware', 'No 38, Udaaludeniya, Weligalla', 9),
('Sampath Moters', 'No 03, Kothmale Road , Nawalapitiya ', 19),
('Sanata Lanka', 'No 49 Sirimalwaththa , Levella ', 6),
('Sanaz Electrical', 'Kurunegala Road, Hedeniya ', 27),
('Sanaz Electrical', 'Kurunegala , Hedeniya', 27),
('Sandagiri Communication / Book Shop', 'No 386, Colombo Road , Pilimathalawa ', 15),
('Sandeepa Aluminium', 'Nawalapitiya Road, Nawalapitya ', 19),
('Sanira Hardware', 'Gonivindala , Pilimathalawa ', 15),
('Sanjaya Enterprises', 'No 511 Aladeniya , Werellagama', 27),
('Sanjeewa Auto Electrical', 'Pallewela , Gampola', 8),
('Sanjeewa Auto Electrical (S.S.R)', 'Pallewela , Gampola', 8),
('Sanji Electronics', 'No 197, Waragollawatta, Gangasirigama, Teldeniya ', 21),
('Sanju Enterprises', '378/B warathenna,Gohada, Gohagoda, Gohagoda', 10),
('Sanka Hardware', 'Samansiri Niwasa , Gurudeniya', 18),
('Sannwey Super', 'No 04/03, Thabiligala Watta, Ulapane', 19),
('Sarasa Book Shop', 'No 454/2, Gadaladeniya Road , Pilimathalawa ', 15),
('Sarasavi Contractions', 'Guhagoda Road , Katugasthota ', 10),
('Sarasavi Electrical', 'Kandy Road , Rikillagaskada', 11),
('Sarwanas Stores', 'No 134  Wahugahapitiya, Pussellawa, Pussellawa', 24),
('Sashiru Multy Center', 'No 02A, Aladeniya Road , Muruthalawa ', 23),
('Sasiru Book Shop', 'No 2/A , Aladeniya Road , Muruthalawa', 23),
('Sathmika Moters', 'No 35/3, Hathamuna, Pilawala', 6),
('Sathsara Auto Parts', 'No 64/2, Arabegama, Pilimathalawa ', 15),
('Sathsiru Fancy', 'No 151/4 Madawala Road, Pollgolla', 17),
('Sathsiru Fancy', 'No 151/4 Madawala Road, Pollgolla', 17),
('Sawesiri Traders', 'Thiththapajjala , Werellagama ', 27),
('SD Moters', 'No 326, Maligathenna Road , Gurudeniya ', 18),
('Sea World Communication', ' No -17/1 Ranawana Road , Pattiyawaththa, Patiyawaththa', 16),
('Senadeera Hardware', 'No 3 Up Juntion , Pujapitiya', 5),
('Senani Stores', 'Wathegama Road , Pollgolla ', 17),
('Senevirathana Stores', 'Rikillagaskada Road, Haguranketha', 11),
('Senevirathana Stores', 'Rikillagaskada Road, Haguranketha', 11),
('Senevirathna Stores', 'No  45 Main Street , Thalathuoya', 25),
('Senevirathna Hardware', 'Main Street , Pujapitiya', 5),
('Senevirathna Hardware', 'Main Street , Pujapitiya', 5),
('Seneviraththana Hw', 'Ehelagasthenna , Pujapitiya', 5),
('Senkadagala Haerware', 'Ranawana Road, Katugasthota ', 10),
('Senkadagala Haerware', 'Ranawana Road, Katugasthota ', 10),
('Senkadagala Hardware', 'No-13 Doranegama Road , Medawala, Medawala', 16),
('Sepali Trade Center', 'No 42 Ragala Road, Rikillagaskada, Rikillagaskada', 11),
('Sepali Trade Center', 'No 21 Main Street , Thalathuoya', 25),
('Serendib Hardware', 'No 485, Peradeniya Road , Kandy ', 13),
('SERENDIP STONE BUNGALOW', 'KUNDASALE', 26),
('Sesatha Hardware', 'No- 83 Katugasthota Road , Polgolla, Polgolla, Madawala', 17),
('Setha Trade Center', 'Main Street, Bokkawala', 16),
('Sewana Grocery', 'No 273/1, Kethigannawala, Mailapitiya ', 11),
('Sha Hardware', 'No 64 B Mahawatha Road, Kundasale ', 26),
('Sha Investment Pvt Ltd', 'No 100, Kurunegala Road , Hedeniya, Werellagama ', 27),
('Shamal Motors', 'No -85/A Mathale Road , Ambathenna , Ambathenna', 5),
('Shambhavi Grocery', 'No 100 Nuwaraeliya Road , Paradeka', 24),
('Shamila steel', 'No 235 Digana Road, thalwaththa', 26),
('Shan Enterprises', 'No 581 Poththapitiya Road, Danthure', 12),
('Shan Food', 'No 345/2 Uyanwaththa , Nugewela', 27),
('Shan Hardware', 'Wathurakubura Road , Kiribathgoda', 12),
('Shani Super', 'Muruthalawa  Road , Gannoruwa ', 23),
('Shantha Hardware', 'No 100 A Gampola Road, Peradeniya', 9),
('Shanthi Hardware', 'Aladeniya Road , Muruthalawa', 23),
('Shanthi stores', 'No 67/2 Dehigama Road, Muruthalawa', 23),
('Shariffdeen and Sons', 'No 545 Main Street , Danthure', 12),
('Sharvind Electrical', 'Nuwaraeliya Road , Pussellawa', 24),
('Shayma Hardware', 'Buwaneka Road, Gampola', 8),
('Shayma Hardware', 'Buwaneka Road, Gampola', 8),
('Sheny Electrical', 'Digana Raod , Balagolla', 14),
('Sheny Electrical', 'Digana Road , Balagolla', 14),
('SHINE LANKA ELECTRICALS', 'No 104/1/1, Ambagamuwa Road , Gampola ', 8),
('Shiva Stores', 'Arangala Road, Natharanpotha', 26),
('Shiwanthini Hardware', 'Kuburegama , Arambekade', 27),
('Shumaka Trading', 'No 247/B, Matale Road , Akurana 07', 4),
('Sigiri Hardware', 'No149, Gamhatha Road, Dawatagahamula', 9),
('Silver Store', 'No 12 Kandy Road , Wathegama, Wathegama', 17),
('Singha Hardware', 'No 293 E, Nawalapitiya Road , Jayamalapura', 19),
('Singhe Stores', 'Nawalapitiya Road, Nawalapitiya', 19),
('Singhe Trades', 'Namalltenna, Galllalla', 16),
('Sinha Giri Hardware', 'Gampola Road, Weligalla', 9),
('Sinha Pali Hardware', 'New Shopping Center , Kandy Road , Oruthota ', 21),
('Sinhapali Hardware', 'Kandy Road , Oruthota', 27),
('Sinhe Hardware', 'no 29 Karalliyadda , Theldeniya ', 21),
('Sinhe Moters', 'No3/3Mallika Waththa , Digana Road, Natharanpotha ', 26),
('Siraj Stores', 'Medawala Road, Uduwawala', 16),
('Siraj Stores', 'Medawala Road, Uduwawala', 16),
('Sirikatha Hardare', 'Thalathuoya Road, Thalathuoya ', 25),
('Sirikatha Hardare', 'Thalathuoya Road, Thalathuoya ', 25),
('Sirira Hardware', 'No 48 Kolongahawaththa , Kengalla', 14),
('Sisira Bake House', 'Bokkawala Road , Amunuthuduwa, Kumburegama', 16),
('Sisira Moters', 'D.S senanayaka Street , Kandyv', 13),
('Sisira Moters', 'D.S senanayaka Street , Kandyv', 13),
('Sisira Stores', 'No 57 Kandy Road, Gurudeniya ', 18),
('Sisira Stores', 'Bokkawala Road , Medawala ', 16),
('Siva Stores', 'Nuwaraeliya Road , Pissellawa', 24),
('Siva Traders', 'No Nuwaraeliya Road , Pussellawa', 24),
('Siwa Traders', 'Nuwaraeliya Road, Pussellawa', 24),
('Sky Electrical', 'No 07 Soysakele Road, Nawalapitiya', 19),
('Slver Traders', 'No 546 Main Street, Danthure', 12),
('Smart car Audio', 'No 356 Colombo Road , Peradeniya', 15),
('Smart Drive', 'No 358, Kandy Road , Akurana ', 4),
('Smart Enterprises', 'No 310, Galaha Road, Hindagala', 7),
('Smart Super', 'No 105, Main Street , Galaha ', 7),
('Smily Mart', 'Madawala Road, Kandy ', 17),
('Smily Mart', 'Madawala Road, Kandy ', 17),
('Solid Oil Mart', 'No 301/A, Kandy Road , Kadugannawa ', 12),
('Solidway Hardware', 'No-21/1 Hapugoda , Pattiyawaththa, Pattiyawaththa', 16),
('Sonee Steel', 'No 36 Digana Road , Kengalla', 14),
('Sooriya Electrical', 'N0 51 Cross Steet, Kandy ', 13),
('Sooriya Traders', 'No 216 Colombo Street, Kandy', 13),
('Spring Hill Hardware', 'no 18/1 Hirrassagala , Kandy', 13),
('Sri Ambal Stores', 'No 16 Pupuressa Road, Galaha', 7),
('Sri Ambal Stores', 'No 16 Pupuressa Road, Galaha', 7),
('Sri Carsons Trading', 'No 42 Colombo Street , Kandy ', 13),
('Sri Comunication', 'No 107 Balagolla , Kengalla', 14),
('Sri dara Hardware', 'no 163/1Lewella Kandy , Kandy', 6),
('Sri Jayalanka Stores', 'No 8/E Narampanawa Road, Manikhinna', 6),
('Sri land Moters', 'Padiyapelella Road, Rikillagaskada ', 11),
('Sri lanka Stores', 'Kothmale Road, Nawalapitiya', 19),
('Sri Laxmi Store', 'No 68 Bopitoya Road , Delthota', 7),
('Sri Nuwan Stores', 'Padiyapellela road, Rikillagaskada', 11),
('Sri Shantha Juwellery', 'No 06 new town digana ', 21),
('Sri Vinoka Stores', 'no 17  Digana Road , Manikhinna ', 6),
('Sri Wijaya Hardware', 'No 165/A Katugasthota Road, Hallouwa', 10),
('Sri Yoga.com', 'No 462 Nuwaraeliya Road, Pussellawa', 24),
('Srimathi Stores', 'Gannoruwa Road, Muruthalawa ', 23),
('Srimathi Super', 'No74/A Kandy Road, Welligalla', 9),
('Sriyananda Stores', 'No638 Senarathgama , Katugasthota ', 27),
('Sriyananda Stores', 'No638 Senarathgama , Katugasthota ', 27),
('Sriyananda Stores', 'No638 Senarathgama , Katugasthota ', 27),
('Sriyananda Stores', 'No638 Senarathgama , Katugasthota ', 27),
('Sriyananda Traders', 'No 54 Sinhapitiya, Gampola ', 8),
('Sriyani Moters', 'Kirinetiya Road, Manikhinna ', 6),
('Star Electrical', 'No 300/B Nuwaraeliya Road, Gampola', 8),
('Strong Concrete', 'No 517 Balagolla , Kengalla', 26),
('Subhani Parmarcy', 'No 07 new Towb , Theldeniya ', 21),
('Sudden City', 'No 73/C Purnawatha , Kandy', 10),
('Sugath Stores', 'No 59, Aladeniya Road , Muruthalawa ', 23),
('Sumaruka Lanka Trading', 'no-390/1 Gohagoda Road, Katugasthota, katugasthota', 10),
('Sumedha Moters', 'No 306 Gampola Road , Peradeniya, Peradeniya', 9),
('Sumedha Moters', 'gampola Road, peradeniya ', 23),
('Sumedha Moters', 'gampola Road, peradeniya ', 23),
('Sumith Hardware and Oil Mart', 'No 75A 12b Boyagama Road, Elugoda', 22),
('Summith Traders', 'No 16 Gampola Road , Gelioya ', 9),
('Sumudu Stores', 'No 30 Colombo Road, Kadugannawa', 12),
('Sumudu Traders', 'New Town , Gurudeniya', 18),
('Sun city Glass', 'No 107 Kurunegala Road, Katugasthota', 10),
('Sun city Glass', 'No 107 Kurunegala Road, Katugasthota', 10),
('Sun Distributors', 'No 1/24, Poojapitiya Road , Ambathenna ', 5),
('Sun Hardware', 'Rikillagaskada Road , Gurudeniya ', 18),
('Sun Moters', 'No 152 A.B.D Senanayaka Street, Kandy ', 13),
('Sun Shine Car', 'No 17/2 Gannoruwa Road, Peradeniya', 23),
('Sun Vision bookshop', 'Nawayalathenna junction , nawayalathenna ', 20),
('SUNRISE CONSORTIUM PRIVATE LIMITED', 'NO 199, NEW DIGANA ROAD, NATHTHARAMPOTHA, KUNDASALE', 26),
('Sunrise Supermaket', 'Digana Road , Kunadasale ', 14),
('Super bike auto care', 'Gampola', 8),
('Super Nine Supermarket', 'Pichchamalwatha Junction , Gurudeniya', 18),
('Suranga Hardware', 'No 324/2, Godamuduna , Muruthalawa ', 23),
('Suranga Moters', 'No 307/C, 05th Mile Post, Nugewela ', 27),
('Suranga Moters', 'No 307 /C 5th post , Nugewela , Katugasthota', 27),
('Susantha Hardware', 'No 447 /1 Nelligahamula Junction, Kiribathkubura', 15),
('Susantha Stores.', 'No - 117 Palipana,, Palipana, Pujapitiya', 5),
('Suwashakthi Moters', 'No 490 A colombo Raod, Pilimathalawa', 12),
('T.G.L Communication', 'No 46 Kandy Road, Kadugannawa', 12),
('T.H PVC HOUSE', 'No 205, Kettawala, Leula, Thalathuoya ', 25),
('T.I.K Stores', 'Kandy Road, Thalathuoya ', 25),
('T.I.K Stores', 'Kandy Road, Thalathuoya ', 25),
('T.P.G Stores', 'No 102 Kandy Road, Kadugannawa', 12),
('T.P.G Stores', 'no 102 kandy Road, kadugannawa', 12),
('Talent Auto Service', 'No 47 , Guhagoda Road , Katugasthota ', 10),
('Teco Electrical', 'No 521 Main Street, Danthure', 12),
('Teldeniya Hardware', 'No 22, New Town , Teldeniya ', 21),
('Tele Tech Elections', 'No 365/1, Kandy Road , Gelioya ', 9),
('Tele tech Electronic', 'peradeniya Road Kandy ', 13),
('Teletech Electronic', 'Peredeniya Road, Kandy', 13),
('Teletech Electronic', 'Peredeniya Road, Kandy', 13),
('Thai Car Audio', 'No 431, Katugasthota Road , Kandy ', 10),
('Thakshila Bookshop', 'No 12 , Main Street , Haguranketha', 11),
('Thanusha Sweet House', 'No 152 Kandy Road, Wathegama', 17),
('Thanusha Sweet House', 'No 152 Kandy Road, Wathegama', 17),
('Tharanga Hardware', 'No 547/1 , Balagolla , Kengalla', 14),
('Tharidu Pothhala', 'Jambugahapitiya Road, Nawayalathenna ', 20),
('Tharushi Hardware', 'Gampola Road, Agunawala ', 9),
('The Book Shop', 'No 118, Digana Road , Kundasale ', 26),
('The International Heardware', 'D.S Senanayaka Road , Kandy', 13),
('The Multi Point', 'No 12 Gampola Road, Penideniya ', 22),
('The National Tire House', 'No 335 Nuwaraeliya Road, Pussellawa', 24),
('The National Tyre Traders', 'No 1335 Nuwaraeliya Road , Pussellawa', 24),
('THE NEW ISLAND TRADERS', 'No 365, Nuwara Eliya Road , Pussellawa ', 24),
('The New National Hardware', 'No 39 Main street Gelioya , Gelioya', 9),
('The Rally Moters', 'No 12 Senanayaka Street, Kandy ', 13),
('The Tile Floor Stores (Gohul hw)', 'No 87/1 Balagolla Kandy Road, Balagolla', 26),
('The Tile Floor Stores (Gohul hw)', 'No 87/1 Balagolla Kandy Road, Balagolla', 26),
('The Tile house', 'Jambugahapitiya junction , Jambugahapitiya', 20),
('Theekshana Store', 'Nawalapitiya Road, Ulapane ', 19),
('Theldeniya Hardware', 'No 22 Nawa Nagaraya, Theldeniya', 21),
('Theldeniya Traders', 'No 396 Balagolla , Kengalla', 14),
('Thennakoon Stores', 'Kopiwatta Road , Girihagama, Kuburegama ', 16),
('Thilak Bake House and Super', 'Main Steet , Bokkawala', 16),
('Thilaka Hardware', 'No 69 Main Street , Thalathuoya', 25),
('Thilaka Hardware', 'No 01 , Hatamuna , Pilawala', 6),
('Thilaka Multy Palece', 'No 03 New Town , Theldeniya', 21),
('Thilakarathna Stores', 'no 59/C Mullegama , Ambathenna ', 5),
('Thilanka Moters', 'Staition Road , Gampola', 8),
('Thilanka Moters', 'Staition Road , Gampola', 8),
('Thilanka Stores', 'Kande Handiya , Hunuwinna', 11),
('Thilkarathna hardware', 'No 71/E Kandy Road, Wathegama ', 17),
('Thintha Kade', 'Kandy Road , Gelioya ', 9),
('Thisew Hardware', 'wathegama Road , Yatiwawala , wathegama, wathegama', 17),
('Thissa hotel', 'Doragamuwa Road, Doraganuwa ', 20),
('Thissa hotel', 'Doragamuwa Road, Doraganuwa ', 20),
('Thissa Stores', 'Maoya, Haguranketha ', 11),
('Thissa Stores', 'Maoya, Haguranketha ', 11),
('Thissa Stores', 'No109 Pichchamalwatha Junction , Gutudeniya ', 18),
('Thissa Stores', 'Kandy Road , Maraasana', 18),
('Thiwanka Hardware', 'No 20/2 Mahakanda , Hindagala', 7),
('thushara stores', 'Kandy Road , Oruthota ', 21),
('thusitha Stores', 'Abilmeegama , Kandy ', 15),
('Tile House', 'Jambugahapitiya Jinction, Jambugahapitiya ', 10),
('Tile House', 'Jambugahapitiya Jinction, Jambugahapitiya ', 10),
('Tirasha Stores', 'Medawala Road, Gonigoda', 16),
('Tirasha Stores', 'Medawala Road, Gonigoda', 16),
('Tokyo Center', 'Kurunegala Road, Katugathota ', 10),
('Top Choice', 'Kandy Road, Gelioya ', 9),
('Toshiba Enterprises', 'No 607 Balagolla Kengalla, kengalla', 14),
('Toshiba Enterprises', 'No 607 Balagolla Kengalla, kengalla', 14),
('Toshibha Enterprises', 'No 551/1 Balagolla , Kengalla', 26),
('Toyo Electrical', 'No 287 Colombo Road , Pilimathalawa', 15),
('Trans WorldCommunication', 'No 110 Kandy Road, Gampola', 8),
('Traranga Trade center', 'Kandy Road, Marassana ', 18),
('Traranga Trade center', 'Kandy Road, Marassana ', 18),
('Tuk Tuk Mart', 'No 248, Kandy Road , Gampola ', 8),
('U K Moters', 'Main Street, Thalathuoya', 25),
('U.K.G Stores', 'No 89 Daulagala Road, Elugoda , Penideniya ', 22),
('U.K.H CONTRACTIONS', 'Shanthi Mahal, Kirinda, Kodiyadeniya, Gampola ', 13),
('U.N.P Saman Hardware', 'No 305/02, Diyapalagoda , Muruthalawa ', 23),
('U.N.P Saman Hardware', 'No 305/02, Diyapalagoda , Muruthalawa ', 23),
('Udadumbara Traders', 'No 25 Old Town , Digana, Rajawella', 14),
('Udapitiya Hardware', 'Sirimalwaththa , Gunnepana', 6),
('Udara Hardware', 'Ampitiya Road, Thalathuoya ', 25),
('Udarata Backery', 'No 66 Pilawala , Gunnepana ', 6),
('Udarata Backery', 'No 66 Pilawala , Gunnepana ', 6),
('Udarata Vegitebles and fruits', 'No 16 Kandy Road, Pikimathalawa', 12),
('udasarani Hardware', 'No 16/2A, Meewathura Road , Peradeniya ', 9),
('UDAYA HARDWARE', 'Panwala, Thalathuoya ', 25),
('Udaya Stores', 'No 01 Karalliyadda , Theldeniya', 21),
('Udaya Stores', '11/1 Yakkagahapitiya , ASirimalwaththa ', 6),
('Udayanga Stores', 'Rajawatta, Bokkawala ', 16),
('Udeshi Moters', 'Main Street , Galaha', 7),
('Udeshi Moters', 'Main Street , Galaha', 7),
('Ududeniya Stores', 'Bopitiya Road, Delthota', 7),
('Udunuwara Hardware', 'No 104 Kandy Road, Wellamboda', 9),
('Ulapane Auto Sub', 'Nawalapitiya Road , Ulapane ', 19),
('Ulapane Auto Sub Ulapane', 'Kandy Road , Ulapane ', 19),
('ULAPANE HARDWARE', 'No 192/4, Nawalapitiya Road , Ulapane ', 19),
('Ultra tec Electronic', 'No 113/D Hijra Place , Kandy Road, Ukuwela', 21),
('Uma Juwellers', 'No 428 Nuwaraeliya Road, Pussellawa', 24),
('Umair Light Shop', 'No 21, Gampola Road , Gelioya ', 9),
('Umanga Stores', 'no 2 A thunkadura , Udathalawinna ', 20),
('Umanga Stores', 'no 2 A thunkadura , Udathalawinna ', 20),
('Uni Part Moters', 'No 17/1, Golf Road , Digana ', 14),
('Unic Moters', 'No 132 Madawala Road, Madawala', 17),
('Union Enterprises', 'No 74/A Kothmale Road , Nawalapitiya', 19),
('United Glass and Stores', 'No 42/A Kandy Road, Gampola', 8),
('United Hardware', 'Buwelikada , Handessa ', 9),
('United Hardware', 'Buwelikada Handessa , Buwelikada ', 22),
('United Hardware', 'Buwelikada Handessa , Buwelikada ', 22),
('United Hardware', 'Little Vally , Delthota ', 7),
('United Hardware', 'Matale Road , Matale ', 4),
('Universel Traders', 'No 1 Nawalapitiya Road, Gampola', 8),
('Unoversal traders', 'No 1 Nawalapitya , Gampola', 8),
('Upali Hardware', 'Kirimetiya Road, Manikhinna', 6),
('Upali Stores', 'Wewela, Bokkawala ', 16),
('Upali Stores', 'No 110, Mathale Road , Ambathenna ', 5),
('Upathissa Grocery', 'no 279 Haguranketha Road, Gurudeniya', 18),
('Upcountry Moters', 'No 52 Kothmale Road, Nawalapitiya', 19),
('Upul Builders', 'Barigama Road .Dulwala, Dulwala, Gohagoda', 10),
('Upul Construction', '5Th Mile Post , Thalathuoya ', 25),
('Upul Construction', '5Th Mile Post , Thalathuoya ', 25),
('Upul products', 'No 60 Cemetry Road, Katudsathota', 10),
('V.G.K Store', 'No 14 new town , Gurudeniya', 18),
('V.R Traders', 'Main Street , Delthota', 7),
('Vanithas fancy', 'Delthota Road, Galaha', 7),
('Vanithas fancy', 'Delthota Road, Galaha', 7),
('Victor Spare parts', 'No 200/B KandyRoad, Wathegama ', 17),
('Victoria Hardware', 'No 5 A Nawalapitiya Road, Gampola', 7),
('Victoria Harware', 'No 5 nawalapitya Road , Gampola', 8),
('Vijaya Bookshop', 'No 40/3 Hewaheta Road, Delthota', 7),
('Vimukthi Hardware', 'Rikillagaskada Road, Gurudeniya ', 18),
('Visithuru Stores', 'No 498 Colombo Road, Kiribathkubura', 15),
('W.N.D.K Grocery', 'Colombo Road, Ambilmeegama', 15),
('Walgampitiya Stores', 'Kirimetiya Road, Manikhinna ', 6),
('Wallmart Eloctronic', 'Doranegama Road , Medawala, Medawala', 16),
('Warathenna Stores', 'Gohagoda road, Gohada, Gohagoda, Gohagoda', 10),
('Waruni stores', 'Maligawatha , Gurudeniya', 18),
('Wasala Hardware', 'thalathuoya Road, Kiudiya handiya ', 18),
('Wasala Stores', 'Kiudiyaroad, puliyadda ', 25),
('Wasana Book shop and Multy', 'Kurunegala Raod , Werellagama ', 27),
('Wasana Hardware', 'Govisewana, Kundasale ', 14),
('Wasana Hardware', 'Peradeniya Road,Kandy , Kandy ', 13),
('Wasana Hardware', 'Peradeniya Road,Kandy , Kandy ', 13),
('WASANA HOLDINGS', 'No 02 B , Buwanekabha Road , Gampola ', 8),
('Wasana Stores', 'no 47 kandy Road, Gurudeniya ', 18),
('Wasatha Moters', 'Nawalapitiya Road , Gampola ', 19),
('Wathegama Hardware', 'no 62 Mathale Road ', 17),
('Wathegama Hardware', 'no 62 Mathale Road ', 17),
('Wathegama Hardware', 'Yakkgahapitiya Junction , Thennakubura', 14),
('Wathegama Hrdware', 'no28 new town , Digana', 14),
('Wathegama Hrdware', 'no28 new town , Digana', 14),
('Wathurakubura Traders', 'No 29 Danthure Road, Pilimathalawa ', 15),
('Wathurakubura Traders', 'No 29 Danthure Road, Pilimathalawa ', 15),
('Wayamba Traders', 'nuwaraeliya Road, Gampola', 8),
('Weerakoon Hwardware', 'Ankubura Raod, Samadithenna', 5),
('Weerakoon Stores', 'Danthure Road, Kiribathkubura ', 15),
('Weerakoon Stores', 'Danthure Road, Kiribathkubura ', 15),
('Weerapaba Trade Cebter', 'No 102 Main Street, Thalathuoya', 13),
('Weerashingha Stores', 'No 173, Nawalapitiya Road , Gampola ', 19),
('Weerasinha Stores', 'No76/B/4 Elugoda, Peradeniya ', 22),
('Welagedara Stores', 'Naranwala, Handessa', 22),
('Welagedara Trading', 'No 26, Malabare Street', 8),
('Welagedara Trading', 'No 26, Malabare Street', 8),
('Welagedara Trading Company', 'No 06 , Buwanekaba Road , Gampola ', 8),
('Weligama Stores', 'No 12 Main street , Muruthalawa', 23),
('Weligama Stores', 'No 12 Main street , Muruthalawa', 23),
('Wellampitiya Kade', 'No 24/B Gannoruwa Road, Peradeniya ', 23),
('Wellampitiya Moters', 'No 2/4/B/13 Gannoruwa Road, PERADENIYA ', 23),
('Wellcome stores', 'no 92 A Colombo Road , peradeniya ', 12),
('Western Electical', 'Colombo Street , Kandy ', 13),
('Westhall Grocery', 'No 38 Kothmale Road, Nawalapitiya', 19),
('Westhall Grocery', 'No 33 Kothmale Road, Nawalapitiya', 19),
('Wickrama Hardware', 'Maluwegama , Gomagoda , Oruthota ', 21),
('Wickrama Hardware', 'Maluwegama , Gomagoda , Oruthota ', 21),
('Wickrama Store', 'No 02 Medawala , Harisspathuwa, Haripathuwa', 16),
('Wickrama Stores', 'No 7 Gurudeniya Road, Thalathuoya', 25),
('Wickrama Stores', 'Siyabalagoda , Danthure ', 15),
('Wickrama Stores', 'Siyambalagoda, Danthure ', 12),
('Wickrama Stores', 'No17, Ranawana Road , Medawala', 16),
('Wijaya Hardware', 'No 365/A paingamuwa , Hindala', 4),
('Wijaya Hardware', 'No 365/A Paningamuwa , Hindagala', 7),
('Wijaya Moters', 'Aladeniya , Werellagama', 27),
('Wijaya Moters (pvt) Ltd', 'No 120 D.S Senanayaka Road, Kandy', 13),
('Wijaya Moters (pvt) Ltd', 'No 120 D.S Senanayaka Road, Kandy', 13),
('WijayaLakshmi Stores', 'No 40/1 Hewaheta Road, Delthotav', 7),
('WijayaLakshmi Stores', 'No 40/1 Hewaheta Road, Delthotav', 7),
('wijekoon Hardware', 'Perawanguwa , Haguranketha ', 11),
('wijekoon Hardware', 'Perawanguwa , Haguranketha ', 11),
('wijesena grocery', 'Kuruduwatha street , kuruduwatha Gampola', 8),
('Wijesinha Hardware', 'No 192 Godawela Doluwa, DOLUWA', 7),
('Wijesinha Hardware', 'No 192 Godawela Doluwa, DOLUWA', 7),
('Wijesinhe Moters', 'No 44 Hospital Road, Gampola', 8),
('Wijethga Hardware', 'Ampitiya  Road , Kandy ', 13),
('Wijitha Hardware', 'No 150/5/1 Nilamba , Galaha', 7),
('Wilson Hardware', 'Heeressagala Road , Kandy, Kandy', 13),
('Wimal vegiteble and Fruits', 'No 355 Nuwaraeliya Road, Pussellawa', 24),
('Wimalasiri Store', 'Kandy Road, Kadugannawa', 12),
('Wimukthi Hardware', 'Lunuwella, Kapuliyadda', 18),
('Win won Communication', 'Kurunegala Road, Nugewala', 27),
('Withana Stores', 'Gampola Road, Ulapane', 19),
('Withanage Traders', 'Kiullida , Kapuliyadha ', 18),
('Y.M.W Aboobacker Store', 'Sirimalwaththa Road, Madawala', 17),
('Yamuna Textile', 'Main Street , Danthure', 12),
('Yasalanka Moters', 'Bus Stand , Haguranketha ', 11),
('Yasiru Book shop', 'Mullegama , Ambathenna ', 5),
('Yasiru Book shop', 'Mullegama , Ambathenna ', 5),
('Yohan Enterprises', 'No 114 J, Palipana, Poojapitiya ', 5),
('Yohan Stores', 'No 261/ A/ 1 , Hedeniya , Werellagama ', 27),
('Yoonus Electrical', 'No-12  Theldeniya Road , Madawala, Madawala', 17),
('Yosuf Stores', 'No 77 New Town, Digana', 14),
('Yosuf Stores', 'No 77 New Town, Digana', 14),
('Yumna Moters', 'Madawala Raod, Madawla', 17),
('Yumna Moters', 'Madawala Raod, Madawla', 17),
('Z.M Alluminium', 'Gelioya Road, Buwelikada', 22),
('Z.M Alluminium', 'Gelioya Road , Buwelikada', 9),
('Zafraz Electrical', 'Madawala Bazar , Madawala', 17),
('Zafraz Electrical', 'Madawala Bazar , Madawala', 17),
('Zain Electrical', 'kalugamuwa Road , Gelioya ', 9),
('Zain Electrical', 'kalugamuwa Road , Gelioya ', 9),
('Zam Zam griding mills', 'Kurunegala Road, Hedeniya', 27),
('Zam Zam Traders', 'No-165/C Wanguwe kade, Madawala Bazar, Madawala, Madawala', 17),
('ZANEX MOTORS', 'No 126, Kothmale Road , Nawalapitiya ', 19),
('Zee Electrcal', '2 nd floor Nawalapitiya Marcket , Nawalapitiya', 19);
